/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiDataset } from './ApiDataset';
import {
    ApiDatasetFromJSON,
    ApiDatasetFromJSONTyped,
    ApiDatasetToJSON,
    ApiDatasetToJSONTyped,
} from './ApiDataset';

/**
 * The list of available datasets. Maps to the /api/available-datasets.json endpoint.
 * @export
 * @interface ApiAvailableDatasets
 */
export interface ApiAvailableDatasets {
    /**
     * The list of datasets that are available in the API.
     * @type {Array<ApiDataset>}
     * @memberof ApiAvailableDatasets
     */
    datasets: Array<ApiDataset>;
}

/**
 * Check if a given object implements the ApiAvailableDatasets interface.
 */
export function instanceOfApiAvailableDatasets(value: object): value is ApiAvailableDatasets {
    if (!('datasets' in value) || value['datasets'] === undefined) return false;
    return true;
}

export function ApiAvailableDatasetsFromJSON(json: any): ApiAvailableDatasets {
    return ApiAvailableDatasetsFromJSONTyped(json, false);
}

export function ApiAvailableDatasetsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAvailableDatasets {
    if (json == null) {
        return json;
    }
    return {
        
        'datasets': ((json['datasets'] as Array<any>).map(ApiDatasetFromJSON)),
    };
}

export function ApiAvailableDatasetsToJSON(json: any): ApiAvailableDatasets {
    return ApiAvailableDatasetsToJSONTyped(json, false);
}

export function ApiAvailableDatasetsToJSONTyped(value?: ApiAvailableDatasets | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'datasets': ((value['datasets'] as Array<any>).map(ApiDatasetToJSON)),
    };
}

