/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiCommentary } from './ApiCommentary';
import {
    ApiCommentaryFromJSON,
    ApiCommentaryFromJSONTyped,
    ApiCommentaryToJSON,
    ApiCommentaryToJSONTyped,
} from './ApiCommentary';

/**
 * The list of available commentaries. Maps to the /api/available-commentaries.json endpoint.
 * @export
 * @interface ApiAvailableCommentaries
 */
export interface ApiAvailableCommentaries {
    /**
     * The list of commentaries that are available in the API.
     * @type {Array<ApiCommentary>}
     * @memberof ApiAvailableCommentaries
     */
    commentaries: Array<ApiCommentary>;
}

/**
 * Check if a given object implements the ApiAvailableCommentaries interface.
 */
export function instanceOfApiAvailableCommentaries(value: object): value is ApiAvailableCommentaries {
    if (!('commentaries' in value) || value['commentaries'] === undefined) return false;
    return true;
}

export function ApiAvailableCommentariesFromJSON(json: any): ApiAvailableCommentaries {
    return ApiAvailableCommentariesFromJSONTyped(json, false);
}

export function ApiAvailableCommentariesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAvailableCommentaries {
    if (json == null) {
        return json;
    }
    return {
        
        'commentaries': ((json['commentaries'] as Array<any>).map(ApiCommentaryFromJSON)),
    };
}

export function ApiAvailableCommentariesToJSON(json: any): ApiAvailableCommentaries {
    return ApiAvailableCommentariesToJSONTyped(json, false);
}

export function ApiAvailableCommentariesToJSONTyped(value?: ApiAvailableCommentaries | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'commentaries': ((value['commentaries'] as Array<any>).map(ApiCommentaryToJSON)),
    };
}

