/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiTranslation } from './ApiTranslation';
import {
    ApiTranslationFromJSON,
    ApiTranslationFromJSONTyped,
    ApiTranslationToJSON,
    ApiTranslationToJSONTyped,
} from './ApiTranslation';

/**
 * The list of available translations. Maps to the /api/available-translations.json endpoint.
 * @export
 * @interface ApiAvailableTranslations
 */
export interface ApiAvailableTranslations {
    /**
     * The list of translations that are available in the API.
     * @type {Array<ApiTranslation>}
     * @memberof ApiAvailableTranslations
     */
    translations: Array<ApiTranslation>;
}

/**
 * Check if a given object implements the ApiAvailableTranslations interface.
 */
export function instanceOfApiAvailableTranslations(value: object): value is ApiAvailableTranslations {
    if (!('translations' in value) || value['translations'] === undefined) return false;
    return true;
}

export function ApiAvailableTranslationsFromJSON(json: any): ApiAvailableTranslations {
    return ApiAvailableTranslationsFromJSONTyped(json, false);
}

export function ApiAvailableTranslationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAvailableTranslations {
    if (json == null) {
        return json;
    }
    return {
        
        'translations': ((json['translations'] as Array<any>).map(ApiTranslationFromJSON)),
    };
}

export function ApiAvailableTranslationsToJSON(json: any): ApiAvailableTranslations {
    return ApiAvailableTranslationsToJSONTyped(json, false);
}

export function ApiAvailableTranslationsToJSONTyped(value?: ApiAvailableTranslations | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'translations': ((value['translations'] as Array<any>).map(ApiTranslationToJSON)),
    };
}

