/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookId } from './BookId';
import {
    BookIdFromJSON,
    BookIdFromJSONTyped,
    BookIdToJSON,
    BookIdToJSONTyped,
} from './BookId';

/**
 * Defines a schema that contains information about a commentary book.
 * @export
 * @interface ApiCommentaryBook
 */
export interface ApiCommentaryBook {
    /**
     * 
     * @type {BookId}
     * @memberof ApiCommentaryBook
     */
    id: BookId;
    /**
     * The name that the commentary provided for the book.
     * @type {string}
     * @memberof ApiCommentaryBook
     */
    name: string;
    /**
     * The common name for the book.
     * @type {string}
     * @memberof ApiCommentaryBook
     */
    commonName: string;
    /**
     * The commentary's introduction for the book. Undefined if the commentary didn't provide an introduction for the book.
     * @type {string}
     * @memberof ApiCommentaryBook
     */
    introduction?: string;
    /**
     * The summary of the commentary's introduction for the book. Undefined if the commentary didn't provide a summary for the book.
     * @type {string}
     * @memberof ApiCommentaryBook
     */
    introductionSummary?: string;
    /**
     * The order of the book in the Bible.
     * @type {number}
     * @memberof ApiCommentaryBook
     */
    order: number;
    /**
     * The number of the first chapter in the book. Null if the comentary book has no chapters.
     * @type {number}
     * @memberof ApiCommentaryBook
     */
    firstChapterNumber: number | null;
    /**
     * The link to the first chapter of the book. Null if the comentary book has no chapters.
     * @type {string}
     * @memberof ApiCommentaryBook
     */
    firstChapterApiLink: string | null;
    /**
     * The number of the last chapter in the book. Null if the comentary book has no chapters.
     * @type {number}
     * @memberof ApiCommentaryBook
     */
    lastChapterNumber: number | null;
    /**
     * The link to the last chapter of the book. Null if the comentary book has no chapters.
     * @type {string}
     * @memberof ApiCommentaryBook
     */
    lastChapterApiLink: string | null;
    /**
     * The number of chapters that the book contains.
     * @type {number}
     * @memberof ApiCommentaryBook
     */
    numberOfChapters: number;
    /**
     * The number of verses that the book contains.
     * @type {number}
     * @memberof ApiCommentaryBook
     */
    totalNumberOfVerses: number;
}



/**
 * Check if a given object implements the ApiCommentaryBook interface.
 */
export function instanceOfApiCommentaryBook(value: object): value is ApiCommentaryBook {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('commonName' in value) || value['commonName'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    if (!('firstChapterNumber' in value) || value['firstChapterNumber'] === undefined) return false;
    if (!('firstChapterApiLink' in value) || value['firstChapterApiLink'] === undefined) return false;
    if (!('lastChapterNumber' in value) || value['lastChapterNumber'] === undefined) return false;
    if (!('lastChapterApiLink' in value) || value['lastChapterApiLink'] === undefined) return false;
    if (!('numberOfChapters' in value) || value['numberOfChapters'] === undefined) return false;
    if (!('totalNumberOfVerses' in value) || value['totalNumberOfVerses'] === undefined) return false;
    return true;
}

export function ApiCommentaryBookFromJSON(json: any): ApiCommentaryBook {
    return ApiCommentaryBookFromJSONTyped(json, false);
}

export function ApiCommentaryBookFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCommentaryBook {
    if (json == null) {
        return json;
    }
    return {
        
        'id': BookIdFromJSON(json['id']),
        'name': json['name'],
        'commonName': json['commonName'],
        'introduction': json['introduction'] == null ? undefined : json['introduction'],
        'introductionSummary': json['introductionSummary'] == null ? undefined : json['introductionSummary'],
        'order': json['order'],
        'firstChapterNumber': json['firstChapterNumber'],
        'firstChapterApiLink': json['firstChapterApiLink'],
        'lastChapterNumber': json['lastChapterNumber'],
        'lastChapterApiLink': json['lastChapterApiLink'],
        'numberOfChapters': json['numberOfChapters'],
        'totalNumberOfVerses': json['totalNumberOfVerses'],
    };
}

export function ApiCommentaryBookToJSON(json: any): ApiCommentaryBook {
    return ApiCommentaryBookToJSONTyped(json, false);
}

export function ApiCommentaryBookToJSONTyped(value?: ApiCommentaryBook | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': BookIdToJSON(value['id']),
        'name': value['name'],
        'commonName': value['commonName'],
        'introduction': value['introduction'],
        'introductionSummary': value['introductionSummary'],
        'order': value['order'],
        'firstChapterNumber': value['firstChapterNumber'],
        'firstChapterApiLink': value['firstChapterApiLink'],
        'lastChapterNumber': value['lastChapterNumber'],
        'lastChapterApiLink': value['lastChapterApiLink'],
        'numberOfChapters': value['numberOfChapters'],
        'totalNumberOfVerses': value['totalNumberOfVerses'],
    };
}

