/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Defines a dataset that is used in the API.
 * @export
 * @interface ApiDataset
 */
export interface ApiDataset {
    /**
     * The ID of the dataset.
     * @type {string}
     * @memberof ApiDataset
     */
    id: string;
    /**
     * The name of the dataset.
     * @type {string}
     * @memberof ApiDataset
     */
    name: string;
    /**
     * The website for the dataset.
     * @type {string}
     * @memberof ApiDataset
     */
    website: string;
    /**
     * The URL that the license for the dataset can be found.
     * @type {string}
     * @memberof ApiDataset
     */
    licenseUrl: string;
    /**
     * The API-added notes for the license.
     * @type {string}
     * @memberof ApiDataset
     */
    licenseNotes?: string | null;
    /**
     * The English name for the dataset.
     * @type {string}
     * @memberof ApiDataset
     */
    englishName: string;
    /**
     * The ISO 639 3-letter language tag that the dataset is primarily in.
     * @type {string}
     * @memberof ApiDataset
     */
    language: string;
    /**
     * The direction that the language is written in.
     * @type {ApiDatasetTextDirectionEnum}
     * @memberof ApiDataset
     */
    textDirection: ApiDatasetTextDirectionEnum;
    /**
     * The API link for the list of books for this dataset. Relative to the API origin.
     * @type {string}
     * @memberof ApiDataset
     */
    listOfBooksApiLink: string;
    /**
     * 
     * @type {Array<ApiDatasetAvailableFormatsEnum>}
     * @memberof ApiDataset
     */
    availableFormats: Array<ApiDatasetAvailableFormatsEnum>;
    /**
     * The number of books that are contained in this dataset.
     * @type {number}
     * @memberof ApiDataset
     */
    numberOfBooks: number;
    /**
     * The total number of chapters that are contained in this dataset.
     * @type {number}
     * @memberof ApiDataset
     */
    totalNumberOfChapters: number;
    /**
     * The total number of verses that are contained in this dataset.
     * @type {number}
     * @memberof ApiDataset
     */
    totalNumberOfVerses: number;
    /**
     * The total number of references that are contained in this dataset.
     * @type {number}
     * @memberof ApiDataset
     */
    totalNumberOfReferences: number;
    /**
     * Gets the name of the language that the dataset is in. Null or undefined if the name of the language is not known.
     * @type {string}
     * @memberof ApiDataset
     */
    languageName?: string;
    /**
     * Gets the name of the language in English. Null or undefined if the language doesn't have an english name.
     * @type {string}
     * @memberof ApiDataset
     */
    languageEnglishName?: string;
}


/**
 * @export
 */
export const ApiDatasetTextDirectionEnum = {
    Ltr: 'ltr',
    Rtl: 'rtl'
} as const;
export type ApiDatasetTextDirectionEnum = typeof ApiDatasetTextDirectionEnum[keyof typeof ApiDatasetTextDirectionEnum];

/**
 * @export
 */
export const ApiDatasetAvailableFormatsEnum = {
    Json: 'json'
} as const;
export type ApiDatasetAvailableFormatsEnum = typeof ApiDatasetAvailableFormatsEnum[keyof typeof ApiDatasetAvailableFormatsEnum];


/**
 * Check if a given object implements the ApiDataset interface.
 */
export function instanceOfApiDataset(value: object): value is ApiDataset {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('website' in value) || value['website'] === undefined) return false;
    if (!('licenseUrl' in value) || value['licenseUrl'] === undefined) return false;
    if (!('englishName' in value) || value['englishName'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('textDirection' in value) || value['textDirection'] === undefined) return false;
    if (!('listOfBooksApiLink' in value) || value['listOfBooksApiLink'] === undefined) return false;
    if (!('availableFormats' in value) || value['availableFormats'] === undefined) return false;
    if (!('numberOfBooks' in value) || value['numberOfBooks'] === undefined) return false;
    if (!('totalNumberOfChapters' in value) || value['totalNumberOfChapters'] === undefined) return false;
    if (!('totalNumberOfVerses' in value) || value['totalNumberOfVerses'] === undefined) return false;
    if (!('totalNumberOfReferences' in value) || value['totalNumberOfReferences'] === undefined) return false;
    return true;
}

export function ApiDatasetFromJSON(json: any): ApiDataset {
    return ApiDatasetFromJSONTyped(json, false);
}

export function ApiDatasetFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDataset {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'website': json['website'],
        'licenseUrl': json['licenseUrl'],
        'licenseNotes': json['licenseNotes'] == null ? undefined : json['licenseNotes'],
        'englishName': json['englishName'],
        'language': json['language'],
        'textDirection': json['textDirection'],
        'listOfBooksApiLink': json['listOfBooksApiLink'],
        'availableFormats': json['availableFormats'],
        'numberOfBooks': json['numberOfBooks'],
        'totalNumberOfChapters': json['totalNumberOfChapters'],
        'totalNumberOfVerses': json['totalNumberOfVerses'],
        'totalNumberOfReferences': json['totalNumberOfReferences'],
        'languageName': json['languageName'] == null ? undefined : json['languageName'],
        'languageEnglishName': json['languageEnglishName'] == null ? undefined : json['languageEnglishName'],
    };
}

export function ApiDatasetToJSON(json: any): ApiDataset {
    return ApiDatasetToJSONTyped(json, false);
}

export function ApiDatasetToJSONTyped(value?: ApiDataset | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'website': value['website'],
        'licenseUrl': value['licenseUrl'],
        'licenseNotes': value['licenseNotes'],
        'englishName': value['englishName'],
        'language': value['language'],
        'textDirection': value['textDirection'],
        'listOfBooksApiLink': value['listOfBooksApiLink'],
        'availableFormats': value['availableFormats'],
        'numberOfBooks': value['numberOfBooks'],
        'totalNumberOfChapters': value['totalNumberOfChapters'],
        'totalNumberOfVerses': value['totalNumberOfVerses'],
        'totalNumberOfReferences': value['totalNumberOfReferences'],
        'languageName': value['languageName'],
        'languageEnglishName': value['languageEnglishName'],
    };
}

