/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Defines a translation that is used in the API.
 * @export
 * @interface ApiTranslation
 */
export interface ApiTranslation {
    /**
     * The ID of the translation.
     * @type {string}
     * @memberof ApiTranslation
     */
    id: string;
    /**
     * The name of the translation.
     * @type {string}
     * @memberof ApiTranslation
     */
    name: string;
    /**
     * The website for the translation.
     * @type {string}
     * @memberof ApiTranslation
     */
    website: string;
    /**
     * The URL that the license for the translation can be found.
     * @type {string}
     * @memberof ApiTranslation
     */
    licenseUrl: string;
    /**
     * The API-added notes for the license.
     * @type {string}
     * @memberof ApiTranslation
     */
    licenseNotes?: string | null;
    /**
     * The notice that should be displayed when displaying content from the translation.
     * @type {string}
     * @memberof ApiTranslation
     */
    licenseNotice?: string | null;
    /**
     * The short name for the translation.
     * @type {string}
     * @memberof ApiTranslation
     */
    shortName?: string;
    /**
     * The English name for the translation.
     * @type {string}
     * @memberof ApiTranslation
     */
    englishName: string;
    /**
     * The ISO 639 3-letter language tag that the translation is primarily in.
     * @type {string}
     * @memberof ApiTranslation
     */
    language: string;
    /**
     * The direction that the language is written in. `ltr` indicates that the text is written from the left side of the page to the right. `rtl` indicates that the text is written from the right side of the page to the left.
     * @type {ApiTranslationTextDirectionEnum}
     * @memberof ApiTranslation
     */
    textDirection: ApiTranslationTextDirectionEnum;
    /**
     * The API link for the list of books for this translation. Relative to the API origin.
     * @type {string}
     * @memberof ApiTranslation
     */
    listOfBooksApiLink: string;
    /**
     * 
     * @type {Array<ApiTranslationAvailableFormatsEnum>}
     * @memberof ApiTranslation
     */
    availableFormats: Array<ApiTranslationAvailableFormatsEnum>;
    /**
     * The number of books that are contained in this translation. Complete translations should have the same number of books as the Bible (66).
     * @type {number}
     * @memberof ApiTranslation
     */
    numberOfBooks: number;
    /**
     * The total number of chapters that are contained in this translation. Complete translations should have the same number of chapters as the Bible (1,189).
     * @type {number}
     * @memberof ApiTranslation
     */
    totalNumberOfChapters: number;
    /**
     * The total number of verses that are contained in this translation. Complete translations should have the same number of verses as the Bible (around 31,102 - some translations exclude verses based on the aparent likelyhood of existing in the original source texts).
     * @type {number}
     * @memberof ApiTranslation
     */
    totalNumberOfVerses: number;
    /**
     * The total number of apocryphal books that are contained in this translation.
     * @type {number}
     * @memberof ApiTranslation
     */
    numberOfApocryphalBooks?: number;
    /**
     * The total number of apocryphal chapters that are contained in this translation.
     * @type {number}
     * @memberof ApiTranslation
     */
    totalNumberOfApocryphalChapters?: number;
    /**
     * The total number of apocryphal verses that are contained in this translation.
     * @type {number}
     * @memberof ApiTranslation
     */
    totalNumberOfApocryphalVerses?: number;
    /**
     * Gets the name of the language that the translation is in. Null or undefined if the name of the language is not known.
     * @type {string}
     * @memberof ApiTranslation
     */
    languageName?: string;
    /**
     * Gets the name of the language in English. Null or undefined if the language doesn't have an english name.
     * @type {string}
     * @memberof ApiTranslation
     */
    languageEnglishName?: string;
    /**
     * The API link for downloading the complete translation as a single JSON file. Relative to the API origin. Undefined if complete translation files are not available.
     * @type {string}
     * @memberof ApiTranslation
     */
    completeTranslationApiLink?: string;
}


/**
 * @export
 */
export const ApiTranslationTextDirectionEnum = {
    Ltr: 'ltr',
    Rtl: 'rtl'
} as const;
export type ApiTranslationTextDirectionEnum = typeof ApiTranslationTextDirectionEnum[keyof typeof ApiTranslationTextDirectionEnum];

/**
 * @export
 */
export const ApiTranslationAvailableFormatsEnum = {
    Json: 'json',
    Usfm: 'usfm'
} as const;
export type ApiTranslationAvailableFormatsEnum = typeof ApiTranslationAvailableFormatsEnum[keyof typeof ApiTranslationAvailableFormatsEnum];


/**
 * Check if a given object implements the ApiTranslation interface.
 */
export function instanceOfApiTranslation(value: object): value is ApiTranslation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('website' in value) || value['website'] === undefined) return false;
    if (!('licenseUrl' in value) || value['licenseUrl'] === undefined) return false;
    if (!('englishName' in value) || value['englishName'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('textDirection' in value) || value['textDirection'] === undefined) return false;
    if (!('listOfBooksApiLink' in value) || value['listOfBooksApiLink'] === undefined) return false;
    if (!('availableFormats' in value) || value['availableFormats'] === undefined) return false;
    if (!('numberOfBooks' in value) || value['numberOfBooks'] === undefined) return false;
    if (!('totalNumberOfChapters' in value) || value['totalNumberOfChapters'] === undefined) return false;
    if (!('totalNumberOfVerses' in value) || value['totalNumberOfVerses'] === undefined) return false;
    return true;
}

export function ApiTranslationFromJSON(json: any): ApiTranslation {
    return ApiTranslationFromJSONTyped(json, false);
}

export function ApiTranslationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTranslation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'website': json['website'],
        'licenseUrl': json['licenseUrl'],
        'licenseNotes': json['licenseNotes'] == null ? undefined : json['licenseNotes'],
        'licenseNotice': json['licenseNotice'] == null ? undefined : json['licenseNotice'],
        'shortName': json['shortName'] == null ? undefined : json['shortName'],
        'englishName': json['englishName'],
        'language': json['language'],
        'textDirection': json['textDirection'],
        'listOfBooksApiLink': json['listOfBooksApiLink'],
        'availableFormats': json['availableFormats'],
        'numberOfBooks': json['numberOfBooks'],
        'totalNumberOfChapters': json['totalNumberOfChapters'],
        'totalNumberOfVerses': json['totalNumberOfVerses'],
        'numberOfApocryphalBooks': json['numberOfApocryphalBooks'] == null ? undefined : json['numberOfApocryphalBooks'],
        'totalNumberOfApocryphalChapters': json['totalNumberOfApocryphalChapters'] == null ? undefined : json['totalNumberOfApocryphalChapters'],
        'totalNumberOfApocryphalVerses': json['totalNumberOfApocryphalVerses'] == null ? undefined : json['totalNumberOfApocryphalVerses'],
        'languageName': json['languageName'] == null ? undefined : json['languageName'],
        'languageEnglishName': json['languageEnglishName'] == null ? undefined : json['languageEnglishName'],
        'completeTranslationApiLink': json['completeTranslationApiLink'] == null ? undefined : json['completeTranslationApiLink'],
    };
}

export function ApiTranslationToJSON(json: any): ApiTranslation {
    return ApiTranslationToJSONTyped(json, false);
}

export function ApiTranslationToJSONTyped(value?: ApiTranslation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'website': value['website'],
        'licenseUrl': value['licenseUrl'],
        'licenseNotes': value['licenseNotes'],
        'licenseNotice': value['licenseNotice'],
        'shortName': value['shortName'],
        'englishName': value['englishName'],
        'language': value['language'],
        'textDirection': value['textDirection'],
        'listOfBooksApiLink': value['listOfBooksApiLink'],
        'availableFormats': value['availableFormats'],
        'numberOfBooks': value['numberOfBooks'],
        'totalNumberOfChapters': value['totalNumberOfChapters'],
        'totalNumberOfVerses': value['totalNumberOfVerses'],
        'numberOfApocryphalBooks': value['numberOfApocryphalBooks'],
        'totalNumberOfApocryphalChapters': value['totalNumberOfApocryphalChapters'],
        'totalNumberOfApocryphalVerses': value['totalNumberOfApocryphalVerses'],
        'languageName': value['languageName'],
        'languageEnglishName': value['languageEnglishName'],
        'completeTranslationApiLink': value['completeTranslationApiLink'],
    };
}

