/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiTranslationBook } from './ApiTranslationBook';
import {
    ApiTranslationBookFromJSON,
    ApiTranslationBookFromJSONTyped,
    ApiTranslationBookToJSON,
    ApiTranslationBookToJSONTyped,
} from './ApiTranslationBook';
import type { ApiTranslation } from './ApiTranslation';
import {
    ApiTranslationFromJSON,
    ApiTranslationFromJSONTyped,
    ApiTranslationToJSON,
    ApiTranslationToJSONTyped,
} from './ApiTranslation';

/**
 * Defines an interface that contains information about the books that are available for a translation.
 * @export
 * @interface ApiTranslationBooks
 */
export interface ApiTranslationBooks {
    /**
     * The translation information for the books.
     * @type {ApiTranslation}
     * @memberof ApiTranslationBooks
     */
    translation: ApiTranslation;
    /**
     * The list of books that are available for the translation.
     * @type {Array<ApiTranslationBook>}
     * @memberof ApiTranslationBooks
     */
    books: Array<ApiTranslationBook>;
}

/**
 * Check if a given object implements the ApiTranslationBooks interface.
 */
export function instanceOfApiTranslationBooks(value: object): value is ApiTranslationBooks {
    if (!('translation' in value) || value['translation'] === undefined) return false;
    if (!('books' in value) || value['books'] === undefined) return false;
    return true;
}

export function ApiTranslationBooksFromJSON(json: any): ApiTranslationBooks {
    return ApiTranslationBooksFromJSONTyped(json, false);
}

export function ApiTranslationBooksFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTranslationBooks {
    if (json == null) {
        return json;
    }
    return {
        
        'translation': ApiTranslationFromJSON(json['translation']),
        'books': ((json['books'] as Array<any>).map(ApiTranslationBookFromJSON)),
    };
}

export function ApiTranslationBooksToJSON(json: any): ApiTranslationBooks {
    return ApiTranslationBooksToJSONTyped(json, false);
}

export function ApiTranslationBooksToJSONTyped(value?: ApiTranslationBooks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'translation': ApiTranslationToJSON(value['translation']),
        'books': ((value['books'] as Array<any>).map(ApiTranslationBookToJSON)),
    };
}

