/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * IDs for books. Follows the USFM standard (https://ubsicap.github.io/usfm/identification/books.html)
 * @export
 */
export const BookId = {
    Gen: 'GEN',
    Exo: 'EXO',
    Lev: 'LEV',
    Num: 'NUM',
    Deu: 'DEU',
    Jos: 'JOS',
    Jdg: 'JDG',
    Rut: 'RUT',
    _1Sa: '1SA',
    _2Sa: '2SA',
    _1Ki: '1KI',
    _2Ki: '2KI',
    _1Ch: '1CH',
    _2Ch: '2CH',
    Ezr: 'EZR',
    Neh: 'NEH',
    Est: 'EST',
    Job: 'JOB',
    Psa: 'PSA',
    Pro: 'PRO',
    Ecc: 'ECC',
    Sng: 'SNG',
    Isa: 'ISA',
    Jer: 'JER',
    Lam: 'LAM',
    Ezk: 'EZK',
    Dan: 'DAN',
    Hos: 'HOS',
    Jol: 'JOL',
    Amo: 'AMO',
    Oba: 'OBA',
    Jon: 'JON',
    Mic: 'MIC',
    Nam: 'NAM',
    Hab: 'HAB',
    Zep: 'ZEP',
    Hag: 'HAG',
    Zec: 'ZEC',
    Mal: 'MAL',
    Mat: 'MAT',
    Mrk: 'MRK',
    Luk: 'LUK',
    Jhn: 'JHN',
    Act: 'ACT',
    Rom: 'ROM',
    _1Co: '1CO',
    _2Co: '2CO',
    Gal: 'GAL',
    Eph: 'EPH',
    Php: 'PHP',
    Col: 'COL',
    _1Th: '1TH',
    _2Th: '2TH',
    _1Ti: '1TI',
    _2Ti: '2TI',
    Tit: 'TIT',
    Phm: 'PHM',
    Heb: 'HEB',
    Jas: 'JAS',
    _1Pe: '1PE',
    _2Pe: '2PE',
    _1Jn: '1JN',
    _2Jn: '2JN',
    _3Jn: '3JN',
    Jud: 'JUD',
    Rev: 'REV',
    Tob: 'TOB',
    Jdt: 'JDT',
    Esg: 'ESG',
    Wis: 'WIS',
    Sir: 'SIR',
    Bar: 'BAR',
    Lje: 'LJE',
    S3Y: 'S3Y',
    Sus: 'SUS',
    Bel: 'BEL',
    _1Ma: '1MA',
    _2Ma: '2MA',
    _3Ma: '3MA',
    _4Ma: '4MA',
    _1Es: '1ES',
    _2Es: '2ES',
    Man: 'MAN',
    Ps2: 'PS2',
    Oda: 'ODA',
    Pss: 'PSS',
    Eza: 'EZA',
    _5Ez: '5EZ',
    _6Ez: '6EZ',
    Dag: 'DAG',
    Ps3: 'PS3',
    _2Ba: '2BA',
    Lba: 'LBA',
    Jub: 'JUB',
    Eno: 'ENO',
    _1Mq: '1MQ',
    _2Mq: '2MQ',
    _3Mq: '3MQ',
    Rep: 'REP',
    _4Ba: '4BA',
    Lao: 'LAO'
} as const;
export type BookId = typeof BookId[keyof typeof BookId];


export function instanceOfBookId(value: any): boolean {
    for (const key in BookId) {
        if (Object.prototype.hasOwnProperty.call(BookId, key)) {
            if (BookId[key as keyof typeof BookId] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BookIdFromJSON(json: any): BookId {
    return BookIdFromJSONTyped(json, false);
}

export function BookIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookId {
    return json as BookId;
}

export function BookIdToJSON(value?: BookId | null): any {
    return value as any;
}

export function BookIdToJSONTyped(value: any, ignoreDiscriminator: boolean): BookId {
    return value as BookId;
}

