/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChapterFootnoteReference } from './ChapterFootnoteReference';
import {
    ChapterFootnoteReferenceFromJSON,
    ChapterFootnoteReferenceFromJSONTyped,
    ChapterFootnoteReferenceToJSON,
    ChapterFootnoteReferenceToJSONTyped,
} from './ChapterFootnoteReference';
import type { ChapterFootnoteCaller } from './ChapterFootnoteCaller';
import {
    ChapterFootnoteCallerFromJSON,
    ChapterFootnoteCallerFromJSONTyped,
    ChapterFootnoteCallerToJSON,
    ChapterFootnoteCallerToJSONTyped,
} from './ChapterFootnoteCaller';

/**
 * Defines the schema for information about a footnote.
 * @export
 * @interface ChapterFootnote
 */
export interface ChapterFootnote {
    /**
     * The ID of the note that is referenced.
     * @type {number}
     * @memberof ChapterFootnote
     */
    noteId: number;
    /**
     * The text of the footnote.
     * @type {string}
     * @memberof ChapterFootnote
     */
    text: string;
    /**
     * 
     * @type {ChapterFootnoteReference}
     * @memberof ChapterFootnote
     */
    reference?: ChapterFootnoteReference;
    /**
     * 
     * @type {ChapterFootnoteCaller}
     * @memberof ChapterFootnote
     */
    caller: ChapterFootnoteCaller | null;
}

/**
 * Check if a given object implements the ChapterFootnote interface.
 */
export function instanceOfChapterFootnote(value: object): value is ChapterFootnote {
    if (!('noteId' in value) || value['noteId'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('caller' in value) || value['caller'] === undefined) return false;
    return true;
}

export function ChapterFootnoteFromJSON(json: any): ChapterFootnote {
    return ChapterFootnoteFromJSONTyped(json, false);
}

export function ChapterFootnoteFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterFootnote {
    if (json == null) {
        return json;
    }
    return {
        
        'noteId': json['noteId'],
        'text': json['text'],
        'reference': json['reference'] == null ? undefined : ChapterFootnoteReferenceFromJSON(json['reference']),
        'caller': ChapterFootnoteCallerFromJSON(json['caller']),
    };
}

export function ChapterFootnoteToJSON(json: any): ChapterFootnote {
    return ChapterFootnoteToJSONTyped(json, false);
}

export function ChapterFootnoteToJSONTyped(value?: ChapterFootnote | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'noteId': value['noteId'],
        'text': value['text'],
        'reference': ChapterFootnoteReferenceToJSON(value['reference']),
        'caller': ChapterFootnoteCallerToJSON(value['caller']),
    };
}

