/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChapterHebrewSubtitleContentInner } from './ChapterHebrewSubtitleContentInner';
import {
    ChapterHebrewSubtitleContentInnerFromJSON,
    ChapterHebrewSubtitleContentInnerFromJSONTyped,
    ChapterHebrewSubtitleContentInnerToJSON,
    ChapterHebrewSubtitleContentInnerToJSONTyped,
} from './ChapterHebrewSubtitleContentInner';

/**
 * Defines the schema for a Hebrew Subtitle in a chapter.
 * @export
 * @interface ChapterHebrewSubtitle
 */
export interface ChapterHebrewSubtitle {
    /**
     * 
     * @type {ChapterHebrewSubtitleTypeEnum}
     * @memberof ChapterHebrewSubtitle
     */
    type: ChapterHebrewSubtitleTypeEnum;
    /**
     * The content that is contained in the subtitle. Each element in the list could be a string, formatted text, or a footnote reference.
     * @type {Array<ChapterHebrewSubtitleContentInner>}
     * @memberof ChapterHebrewSubtitle
     */
    content: Array<ChapterHebrewSubtitleContentInner>;
}


/**
 * @export
 */
export const ChapterHebrewSubtitleTypeEnum = {
    HebrewSubtitle: 'hebrew_subtitle'
} as const;
export type ChapterHebrewSubtitleTypeEnum = typeof ChapterHebrewSubtitleTypeEnum[keyof typeof ChapterHebrewSubtitleTypeEnum];


/**
 * Check if a given object implements the ChapterHebrewSubtitle interface.
 */
export function instanceOfChapterHebrewSubtitle(value: object): value is ChapterHebrewSubtitle {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function ChapterHebrewSubtitleFromJSON(json: any): ChapterHebrewSubtitle {
    return ChapterHebrewSubtitleFromJSONTyped(json, false);
}

export function ChapterHebrewSubtitleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterHebrewSubtitle {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'content': ((json['content'] as Array<any>).map(ChapterHebrewSubtitleContentInnerFromJSON)),
    };
}

export function ChapterHebrewSubtitleToJSON(json: any): ChapterHebrewSubtitle {
    return ChapterHebrewSubtitleToJSONTyped(json, false);
}

export function ChapterHebrewSubtitleToJSONTyped(value?: ChapterHebrewSubtitle | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'content': ((value['content'] as Array<any>).map(ChapterHebrewSubtitleContentInnerToJSON)),
    };
}

