/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ChapterHeading } from './ChapterHeading';
import {
    instanceOfChapterHeading,
    ChapterHeadingFromJSON,
    ChapterHeadingFromJSONTyped,
    ChapterHeadingToJSON,
} from './ChapterHeading';
import type { ChapterHebrewSubtitle } from './ChapterHebrewSubtitle';
import {
    instanceOfChapterHebrewSubtitle,
    ChapterHebrewSubtitleFromJSON,
    ChapterHebrewSubtitleFromJSONTyped,
    ChapterHebrewSubtitleToJSON,
} from './ChapterHebrewSubtitle';
import type { ChapterLineBreak } from './ChapterLineBreak';
import {
    instanceOfChapterLineBreak,
    ChapterLineBreakFromJSON,
    ChapterLineBreakFromJSONTyped,
    ChapterLineBreakToJSON,
} from './ChapterLineBreak';
import type { ChapterVerse } from './ChapterVerse';
import {
    instanceOfChapterVerse,
    ChapterVerseFromJSON,
    ChapterVerseFromJSONTyped,
    ChapterVerseToJSON,
} from './ChapterVerse';

/**
 * @type ChapterContent
 * Defines a union type that represents a single piece of chapter content. A piece of chapter content can be one of the following things: A heading, a line break, a verse, or a Hebrew Subtitle.
 * @export
 */
export type ChapterContent = { type: 'heading' } & ChapterHeading | { type: 'hebrew_subtitle' } & ChapterHebrewSubtitle | { type: 'line_break' } & ChapterLineBreak | { type: 'verse' } & ChapterVerse;

export function ChapterContentFromJSON(json: any): ChapterContent {
    return ChapterContentFromJSONTyped(json, false);
}

export function ChapterContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterContent {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'heading':
            return Object.assign({}, ChapterHeadingFromJSONTyped(json, true), { type: 'heading' } as const);
        case 'hebrew_subtitle':
            return Object.assign({}, ChapterHebrewSubtitleFromJSONTyped(json, true), { type: 'hebrew_subtitle' } as const);
        case 'line_break':
            return Object.assign({}, ChapterLineBreakFromJSONTyped(json, true), { type: 'line_break' } as const);
        case 'verse':
            return Object.assign({}, ChapterVerseFromJSONTyped(json, true), { type: 'verse' } as const);
        default:
            return json;
    }
}

export function ChapterContentToJSON(json: any): any {
    return ChapterContentToJSONTyped(json, false);
}

export function ChapterContentToJSONTyped(value?: ChapterContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'heading':
            return Object.assign({}, ChapterHeadingToJSON(value), { type: 'heading' } as const);
        case 'hebrew_subtitle':
            return Object.assign({}, ChapterHebrewSubtitleToJSON(value), { type: 'hebrew_subtitle' } as const);
        case 'line_break':
            return Object.assign({}, ChapterLineBreakToJSON(value), { type: 'line_break' } as const);
        case 'verse':
            return Object.assign({}, ChapterVerseToJSON(value), { type: 'verse' } as const);
        default:
            return value;
    }
}

