/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The verse reference for the footnote. Undefined if the footnote isn't associated with a specific verse.
 * @export
 * @interface ChapterFootnoteReference
 */
export interface ChapterFootnoteReference {
    /**
     * 
     * @type {number}
     * @memberof ChapterFootnoteReference
     */
    chapter: number;
    /**
     * 
     * @type {number}
     * @memberof ChapterFootnoteReference
     */
    verse: number;
}

/**
 * Check if a given object implements the ChapterFootnoteReference interface.
 */
export function instanceOfChapterFootnoteReference(value: object): value is ChapterFootnoteReference {
    if (!('chapter' in value) || value['chapter'] === undefined) return false;
    if (!('verse' in value) || value['verse'] === undefined) return false;
    return true;
}

export function ChapterFootnoteReferenceFromJSON(json: any): ChapterFootnoteReference {
    return ChapterFootnoteReferenceFromJSONTyped(json, false);
}

export function ChapterFootnoteReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterFootnoteReference {
    if (json == null) {
        return json;
    }
    return {
        
        'chapter': json['chapter'],
        'verse': json['verse'],
    };
}

export function ChapterFootnoteReferenceToJSON(json: any): ChapterFootnoteReference {
    return ChapterFootnoteReferenceToJSONTyped(json, false);
}

export function ChapterFootnoteReferenceToJSONTyped(value?: ChapterFootnoteReference | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapter': value['chapter'],
        'verse': value['verse'],
    };
}

