/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Defines the schema for a line break in a chapter.
 * @export
 * @interface ChapterLineBreak
 */
export interface ChapterLineBreak {
    /**
     * 
     * @type {ChapterLineBreakTypeEnum}
     * @memberof ChapterLineBreak
     */
    type: ChapterLineBreakTypeEnum;
}


/**
 * @export
 */
export const ChapterLineBreakTypeEnum = {
    LineBreak: 'line_break'
} as const;
export type ChapterLineBreakTypeEnum = typeof ChapterLineBreakTypeEnum[keyof typeof ChapterLineBreakTypeEnum];


/**
 * Check if a given object implements the ChapterLineBreak interface.
 */
export function instanceOfChapterLineBreak(value: object): value is ChapterLineBreak {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function ChapterLineBreakFromJSON(json: any): ChapterLineBreak {
    return ChapterLineBreakFromJSONTyped(json, false);
}

export function ChapterLineBreakFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterLineBreak {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function ChapterLineBreakToJSON(json: any): ChapterLineBreak {
    return ChapterLineBreakToJSONTyped(json, false);
}

export function ChapterLineBreakToJSONTyped(value?: ChapterLineBreak | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

