/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ScoredVerseRef } from './ScoredVerseRef';
import {
    ScoredVerseRefFromJSON,
    ScoredVerseRefFromJSONTyped,
    ScoredVerseRefToJSON,
    ScoredVerseRefToJSONTyped,
} from './ScoredVerseRef';

/**
 * Defines the schema for information about a verse in a dataset chapter.
 * @export
 * @interface DatasetChapterVerseContent
 */
export interface DatasetChapterVerseContent {
    /**
     * The number of the verse.
     * @type {number}
     * @memberof DatasetChapterVerseContent
     */
    verse: number;
    /**
     * The list of references for the verse.
     * @type {Array<ScoredVerseRef>}
     * @memberof DatasetChapterVerseContent
     */
    references: Array<ScoredVerseRef>;
}

/**
 * Check if a given object implements the DatasetChapterVerseContent interface.
 */
export function instanceOfDatasetChapterVerseContent(value: object): value is DatasetChapterVerseContent {
    if (!('verse' in value) || value['verse'] === undefined) return false;
    if (!('references' in value) || value['references'] === undefined) return false;
    return true;
}

export function DatasetChapterVerseContentFromJSON(json: any): DatasetChapterVerseContent {
    return DatasetChapterVerseContentFromJSONTyped(json, false);
}

export function DatasetChapterVerseContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetChapterVerseContent {
    if (json == null) {
        return json;
    }
    return {
        
        'verse': json['verse'],
        'references': ((json['references'] as Array<any>).map(ScoredVerseRefFromJSON)),
    };
}

export function DatasetChapterVerseContentToJSON(json: any): DatasetChapterVerseContent {
    return DatasetChapterVerseContentToJSONTyped(json, false);
}

export function DatasetChapterVerseContentToJSONTyped(value?: DatasetChapterVerseContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'verse': value['verse'],
        'references': ((value['references'] as Array<any>).map(ScoredVerseRefToJSON)),
    };
}

