/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Defines the schema for formatted text. That is, text that is formatted in a particular manner.
 * @export
 * @interface FormattedText
 */
export interface FormattedText {
    /**
     * The text that is formatted.
     * @type {string}
     * @memberof FormattedText
     */
    text: string;
    /**
     * Whether the text represents a poem. The number indicates the level of indent. Common in Psalms.
     * @type {number}
     * @memberof FormattedText
     */
    poem?: number;
    /**
     * Whether the text represents the Words of Jesus.
     * @type {boolean}
     * @memberof FormattedText
     */
    wordsOfJesus?: boolean;
}

/**
 * Check if a given object implements the FormattedText interface.
 */
export function instanceOfFormattedText(value: object): value is FormattedText {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function FormattedTextFromJSON(json: any): FormattedText {
    return FormattedTextFromJSONTyped(json, false);
}

export function FormattedTextFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormattedText {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'poem': json['poem'] == null ? undefined : json['poem'],
        'wordsOfJesus': json['wordsOfJesus'] == null ? undefined : json['wordsOfJesus'],
    };
}

export function FormattedTextToJSON(json: any): FormattedText {
    return FormattedTextToJSONTyped(json, false);
}

export function FormattedTextToJSONTyped(value?: FormattedText | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'poem': value['poem'],
        'wordsOfJesus': value['wordsOfJesus'],
    };
}

