/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Defines the schema for a line break that is embedded in a verse.
 * @export
 * @interface InlineLineBreak
 */
export interface InlineLineBreak {
    /**
     * 
     * @type {InlineLineBreakLineBreakEnum}
     * @memberof InlineLineBreak
     */
    lineBreak: InlineLineBreakLineBreakEnum;
}


/**
 * @export
 */
export const InlineLineBreakLineBreakEnum = {
    True: true
} as const;
export type InlineLineBreakLineBreakEnum = typeof InlineLineBreakLineBreakEnum[keyof typeof InlineLineBreakLineBreakEnum];


/**
 * Check if a given object implements the InlineLineBreak interface.
 */
export function instanceOfInlineLineBreak(value: object): value is InlineLineBreak {
    if (!('lineBreak' in value) || value['lineBreak'] === undefined) return false;
    return true;
}

export function InlineLineBreakFromJSON(json: any): InlineLineBreak {
    return InlineLineBreakFromJSONTyped(json, false);
}

export function InlineLineBreakFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineLineBreak {
    if (json == null) {
        return json;
    }
    return {
        
        'lineBreak': json['lineBreak'],
    };
}

export function InlineLineBreakToJSON(json: any): InlineLineBreak {
    return InlineLineBreakToJSONTyped(json, false);
}

export function InlineLineBreakToJSONTyped(value?: InlineLineBreak | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lineBreak': value['lineBreak'],
    };
}

