/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Defines the schema for a heading that is embedded in a verse.
 * @export
 * @interface InlineHeading
 */
export interface InlineHeading {
    /**
     * The text of the heading.
     * @type {string}
     * @memberof InlineHeading
     */
    heading: string;
}

/**
 * Check if a given object implements the InlineHeading interface.
 */
export function instanceOfInlineHeading(value: object): value is InlineHeading {
    if (!('heading' in value) || value['heading'] === undefined) return false;
    return true;
}

export function InlineHeadingFromJSON(json: any): InlineHeading {
    return InlineHeadingFromJSONTyped(json, false);
}

export function InlineHeadingFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineHeading {
    if (json == null) {
        return json;
    }
    return {
        
        'heading': json['heading'],
    };
}

export function InlineHeadingToJSON(json: any): InlineHeading {
    return InlineHeadingToJSONTyped(json, false);
}

export function InlineHeadingToJSONTyped(value?: InlineHeading | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'heading': value['heading'],
    };
}

