/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookId } from './BookId';
import {
    BookIdFromJSON,
    BookIdFromJSONTyped,
    BookIdToJSON,
    BookIdToJSONTyped,
} from './BookId';

/**
 * Defines the schema for information about a verse reference that has an arbitrary score attached to it.
 * @export
 * @interface ScoredVerseRef
 */
export interface ScoredVerseRef {
    /**
     * 
     * @type {BookId}
     * @memberof ScoredVerseRef
     */
    book: BookId;
    /**
     * The chapter number that the reference starts at.
     * @type {number}
     * @memberof ScoredVerseRef
     */
    chapter: number;
    /**
     * The verse number that the reference starts at.
     * @type {number}
     * @memberof ScoredVerseRef
     */
    verse: number;
    /**
     * The rest of the content of the verse reference. This is the part of the string that comes after the verse reference. For example, in "GEN 1:1 In the beginning, God created the Heavens and the Earth.", the content would be "In the beginning, God created the Heavens and the Earth."
     * @type {string}
     * @memberof ScoredVerseRef
     */
    content?: string;
    /**
     * The chapter that the verse reference ends at. This is used for references that span multiple chapters, such as "GEN 1:1-2:3". In this case, the endChapter would be 2.
     * @type {number}
     * @memberof ScoredVerseRef
     */
    endChapter?: number;
    /**
     * The verse that the verse reference ends at. This is used for references that span multiple verses, such as "GEN 1:1-1:3". In this case, the endVerse would be 3.
     * @type {number}
     * @memberof ScoredVerseRef
     */
    endVerse?: number;
    /**
     * The score for the verse reference. The meaning of the score is arbitrary and is determined by the dataset.
     * @type {number}
     * @memberof ScoredVerseRef
     */
    score: number;
}



/**
 * Check if a given object implements the ScoredVerseRef interface.
 */
export function instanceOfScoredVerseRef(value: object): value is ScoredVerseRef {
    if (!('book' in value) || value['book'] === undefined) return false;
    if (!('chapter' in value) || value['chapter'] === undefined) return false;
    if (!('verse' in value) || value['verse'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    return true;
}

export function ScoredVerseRefFromJSON(json: any): ScoredVerseRef {
    return ScoredVerseRefFromJSONTyped(json, false);
}

export function ScoredVerseRefFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoredVerseRef {
    if (json == null) {
        return json;
    }
    return {
        
        'book': BookIdFromJSON(json['book']),
        'chapter': json['chapter'],
        'verse': json['verse'],
        'content': json['content'] == null ? undefined : json['content'],
        'endChapter': json['endChapter'] == null ? undefined : json['endChapter'],
        'endVerse': json['endVerse'] == null ? undefined : json['endVerse'],
        'score': json['score'],
    };
}

export function ScoredVerseRefToJSON(json: any): ScoredVerseRef {
    return ScoredVerseRefToJSONTyped(json, false);
}

export function ScoredVerseRefToJSONTyped(value?: ScoredVerseRef | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'book': BookIdToJSON(value['book']),
        'chapter': value['chapter'],
        'verse': value['verse'],
        'content': value['content'],
        'endChapter': value['endChapter'],
        'endVerse': value['endVerse'],
        'score': value['score'],
    };
}

