/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Defines the schema for a footnote reference in a verse or a Hebrew Subtitle.
 * @export
 * @interface VerseFootnoteReference
 */
export interface VerseFootnoteReference {
    /**
     * The ID of the note.
     * @type {number}
     * @memberof VerseFootnoteReference
     */
    noteId: number;
}

/**
 * Check if a given object implements the VerseFootnoteReference interface.
 */
export function instanceOfVerseFootnoteReference(value: object): value is VerseFootnoteReference {
    if (!('noteId' in value) || value['noteId'] === undefined) return false;
    return true;
}

export function VerseFootnoteReferenceFromJSON(json: any): VerseFootnoteReference {
    return VerseFootnoteReferenceFromJSONTyped(json, false);
}

export function VerseFootnoteReferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerseFootnoteReference {
    if (json == null) {
        return json;
    }
    return {
        
        'noteId': json['noteId'],
    };
}

export function VerseFootnoteReferenceToJSON(json: any): VerseFootnoteReference {
    return VerseFootnoteReferenceToJSONTyped(json, false);
}

export function VerseFootnoteReferenceToJSONTyped(value?: VerseFootnoteReference | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'noteId': value['noteId'],
    };
}

