/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ApiAvailableCommentaries,
    ApiAvailableCommentariesFromJSON,
    ApiAvailableCommentariesToJSON,
} from '../models/ApiAvailableCommentaries';
import {
    type ApiAvailableDatasets,
    ApiAvailableDatasetsFromJSON,
    ApiAvailableDatasetsToJSON,
} from '../models/ApiAvailableDatasets';
import {
    type ApiAvailableTranslations,
    ApiAvailableTranslationsFromJSON,
    ApiAvailableTranslationsToJSON,
} from '../models/ApiAvailableTranslations';
import {
    type ApiCommentaryBookChapter,
    ApiCommentaryBookChapterFromJSON,
    ApiCommentaryBookChapterToJSON,
} from '../models/ApiCommentaryBookChapter';
import {
    type ApiCommentaryBooks,
    ApiCommentaryBooksFromJSON,
    ApiCommentaryBooksToJSON,
} from '../models/ApiCommentaryBooks';
import {
    type ApiDatasetBookChapter,
    ApiDatasetBookChapterFromJSON,
    ApiDatasetBookChapterToJSON,
} from '../models/ApiDatasetBookChapter';
import {
    type ApiDatasetBooks,
    ApiDatasetBooksFromJSON,
    ApiDatasetBooksToJSON,
} from '../models/ApiDatasetBooks';
import {
    type ApiTranslationBookChapter,
    ApiTranslationBookChapterFromJSON,
    ApiTranslationBookChapterToJSON,
} from '../models/ApiTranslationBookChapter';
import {
    type ApiTranslationBooks,
    ApiTranslationBooksFromJSON,
    ApiTranslationBooksToJSON,
} from '../models/ApiTranslationBooks';
import {
    type ApiTranslationComplete,
    ApiTranslationCompleteFromJSON,
    ApiTranslationCompleteToJSON,
} from '../models/ApiTranslationComplete';
import {
    type BookId,
    BookIdFromJSON,
    BookIdToJSON,
} from '../models/BookId';

export interface GetCommentaryBookChapterRequest {
    commentary: string;
    book: BookId;
    chapter: number;
}

export interface GetCommentaryBooksRequest {
    commentary: string;
}

export interface GetDatasetBookChapterRequest {
    dataset: string;
    book: BookId;
    chapter: number;
}

export interface GetDatasetBooksRequest {
    dataset: string;
}

export interface GetTranslationBookChapterRequest {
    translation: string;
    book: BookId;
    chapter: number;
}

export interface GetTranslationBooksRequest {
    translation: string;
}

export interface GetTranslationCompleteRequest {
    translation: string;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for getAvailableCommentaries without sending the request
     */
    async getAvailableCommentariesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/available_commentaries.json`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the list of available commentaries.
     */
    async getAvailableCommentariesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiAvailableCommentaries>> {
        const requestOptions = await this.getAvailableCommentariesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiAvailableCommentariesFromJSON(jsonValue));
    }

    /**
     * Get the list of available commentaries.
     */
    async getAvailableCommentaries(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiAvailableCommentaries> {
        const response = await this.getAvailableCommentariesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAvailableDatasets without sending the request
     */
    async getAvailableDatasetsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/available_datasets.json`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the list of available datasets.
     */
    async getAvailableDatasetsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiAvailableDatasets>> {
        const requestOptions = await this.getAvailableDatasetsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiAvailableDatasetsFromJSON(jsonValue));
    }

    /**
     * Get the list of available datasets.
     */
    async getAvailableDatasets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiAvailableDatasets> {
        const response = await this.getAvailableDatasetsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAvailableTranslations without sending the request
     */
    async getAvailableTranslationsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/available_translations.json`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the list of available Bible translations.
     */
    async getAvailableTranslationsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiAvailableTranslations>> {
        const requestOptions = await this.getAvailableTranslationsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiAvailableTranslationsFromJSON(jsonValue));
    }

    /**
     * Get the list of available Bible translations.
     */
    async getAvailableTranslations(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiAvailableTranslations> {
        const response = await this.getAvailableTranslationsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCommentaryBookChapter without sending the request
     */
    async getCommentaryBookChapterRequestOpts(requestParameters: GetCommentaryBookChapterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commentary'] == null) {
            throw new runtime.RequiredError(
                'commentary',
                'Required parameter "commentary" was null or undefined when calling getCommentaryBookChapter().'
            );
        }

        if (requestParameters['book'] == null) {
            throw new runtime.RequiredError(
                'book',
                'Required parameter "book" was null or undefined when calling getCommentaryBookChapter().'
            );
        }

        if (requestParameters['chapter'] == null) {
            throw new runtime.RequiredError(
                'chapter',
                'Required parameter "chapter" was null or undefined when calling getCommentaryBookChapter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/c/{commentary}/{book}/{chapter}.json`;
        urlPath = urlPath.replace('{commentary}', encodeURIComponent(String(requestParameters['commentary'])));
        urlPath = urlPath.replace('{book}', encodeURIComponent(String(requestParameters['book'])));
        urlPath = urlPath.replace('{chapter}', encodeURIComponent(String(requestParameters['chapter'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the content of a specific chapter of a specific book for a specific commentary.
     */
    async getCommentaryBookChapterRaw(requestParameters: GetCommentaryBookChapterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiCommentaryBookChapter>> {
        const requestOptions = await this.getCommentaryBookChapterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiCommentaryBookChapterFromJSON(jsonValue));
    }

    /**
     * Get the content of a specific chapter of a specific book for a specific commentary.
     */
    async getCommentaryBookChapter(requestParameters: GetCommentaryBookChapterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiCommentaryBookChapter> {
        const response = await this.getCommentaryBookChapterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCommentaryBooks without sending the request
     */
    async getCommentaryBooksRequestOpts(requestParameters: GetCommentaryBooksRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['commentary'] == null) {
            throw new runtime.RequiredError(
                'commentary',
                'Required parameter "commentary" was null or undefined when calling getCommentaryBooks().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/c/{commentary}/books.json`;
        urlPath = urlPath.replace('{commentary}', encodeURIComponent(String(requestParameters['commentary'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the list of books available for a specific commentary.
     */
    async getCommentaryBooksRaw(requestParameters: GetCommentaryBooksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiCommentaryBooks>> {
        const requestOptions = await this.getCommentaryBooksRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiCommentaryBooksFromJSON(jsonValue));
    }

    /**
     * Get the list of books available for a specific commentary.
     */
    async getCommentaryBooks(requestParameters: GetCommentaryBooksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiCommentaryBooks> {
        const response = await this.getCommentaryBooksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDatasetBookChapter without sending the request
     */
    async getDatasetBookChapterRequestOpts(requestParameters: GetDatasetBookChapterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dataset'] == null) {
            throw new runtime.RequiredError(
                'dataset',
                'Required parameter "dataset" was null or undefined when calling getDatasetBookChapter().'
            );
        }

        if (requestParameters['book'] == null) {
            throw new runtime.RequiredError(
                'book',
                'Required parameter "book" was null or undefined when calling getDatasetBookChapter().'
            );
        }

        if (requestParameters['chapter'] == null) {
            throw new runtime.RequiredError(
                'chapter',
                'Required parameter "chapter" was null or undefined when calling getDatasetBookChapter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/d/{dataset}/{book}/{chapter}.json`;
        urlPath = urlPath.replace('{dataset}', encodeURIComponent(String(requestParameters['dataset'])));
        urlPath = urlPath.replace('{book}', encodeURIComponent(String(requestParameters['book'])));
        urlPath = urlPath.replace('{chapter}', encodeURIComponent(String(requestParameters['chapter'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the content of a specific chapter of a specific book for a specific dataset.
     */
    async getDatasetBookChapterRaw(requestParameters: GetDatasetBookChapterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiDatasetBookChapter>> {
        const requestOptions = await this.getDatasetBookChapterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiDatasetBookChapterFromJSON(jsonValue));
    }

    /**
     * Get the content of a specific chapter of a specific book for a specific dataset.
     */
    async getDatasetBookChapter(requestParameters: GetDatasetBookChapterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiDatasetBookChapter> {
        const response = await this.getDatasetBookChapterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getDatasetBooks without sending the request
     */
    async getDatasetBooksRequestOpts(requestParameters: GetDatasetBooksRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['dataset'] == null) {
            throw new runtime.RequiredError(
                'dataset',
                'Required parameter "dataset" was null or undefined when calling getDatasetBooks().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/d/{dataset}/books.json`;
        urlPath = urlPath.replace('{dataset}', encodeURIComponent(String(requestParameters['dataset'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the list of books available for a specific dataset.
     */
    async getDatasetBooksRaw(requestParameters: GetDatasetBooksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiDatasetBooks>> {
        const requestOptions = await this.getDatasetBooksRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiDatasetBooksFromJSON(jsonValue));
    }

    /**
     * Get the list of books available for a specific dataset.
     */
    async getDatasetBooks(requestParameters: GetDatasetBooksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiDatasetBooks> {
        const response = await this.getDatasetBooksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTranslationBookChapter without sending the request
     */
    async getTranslationBookChapterRequestOpts(requestParameters: GetTranslationBookChapterRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['translation'] == null) {
            throw new runtime.RequiredError(
                'translation',
                'Required parameter "translation" was null or undefined when calling getTranslationBookChapter().'
            );
        }

        if (requestParameters['book'] == null) {
            throw new runtime.RequiredError(
                'book',
                'Required parameter "book" was null or undefined when calling getTranslationBookChapter().'
            );
        }

        if (requestParameters['chapter'] == null) {
            throw new runtime.RequiredError(
                'chapter',
                'Required parameter "chapter" was null or undefined when calling getTranslationBookChapter().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/{translation}/{book}/{chapter}.json`;
        urlPath = urlPath.replace('{translation}', encodeURIComponent(String(requestParameters['translation'])));
        urlPath = urlPath.replace('{book}', encodeURIComponent(String(requestParameters['book'])));
        urlPath = urlPath.replace('{chapter}', encodeURIComponent(String(requestParameters['chapter'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the content of a specific chapter of a specific book for a specific translation.
     */
    async getTranslationBookChapterRaw(requestParameters: GetTranslationBookChapterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiTranslationBookChapter>> {
        const requestOptions = await this.getTranslationBookChapterRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiTranslationBookChapterFromJSON(jsonValue));
    }

    /**
     * Get the content of a specific chapter of a specific book for a specific translation.
     */
    async getTranslationBookChapter(requestParameters: GetTranslationBookChapterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiTranslationBookChapter> {
        const response = await this.getTranslationBookChapterRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTranslationBooks without sending the request
     */
    async getTranslationBooksRequestOpts(requestParameters: GetTranslationBooksRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['translation'] == null) {
            throw new runtime.RequiredError(
                'translation',
                'Required parameter "translation" was null or undefined when calling getTranslationBooks().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/{translation}/books.json`;
        urlPath = urlPath.replace('{translation}', encodeURIComponent(String(requestParameters['translation'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the list of books available for a specific translation.
     */
    async getTranslationBooksRaw(requestParameters: GetTranslationBooksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiTranslationBooks>> {
        const requestOptions = await this.getTranslationBooksRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiTranslationBooksFromJSON(jsonValue));
    }

    /**
     * Get the list of books available for a specific translation.
     */
    async getTranslationBooks(requestParameters: GetTranslationBooksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiTranslationBooks> {
        const response = await this.getTranslationBooksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTranslationComplete without sending the request
     */
    async getTranslationCompleteRequestOpts(requestParameters: GetTranslationCompleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['translation'] == null) {
            throw new runtime.RequiredError(
                'translation',
                'Required parameter "translation" was null or undefined when calling getTranslationComplete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/{translation}/complete.json`;
        urlPath = urlPath.replace('{translation}', encodeURIComponent(String(requestParameters['translation'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the complete content of a specific translation.
     */
    async getTranslationCompleteRaw(requestParameters: GetTranslationCompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiTranslationComplete>> {
        const requestOptions = await this.getTranslationCompleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiTranslationCompleteFromJSON(jsonValue));
    }

    /**
     * Get the complete content of a specific translation.
     */
    async getTranslationComplete(requestParameters: GetTranslationCompleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiTranslationComplete> {
        const response = await this.getTranslationCompleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
