/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Defines a commentary that is used in the API.
 * @export
 * @interface ApiCommentary
 */
export interface ApiCommentary {
    /**
     * The ID of the commentary.
     * @type {string}
     * @memberof ApiCommentary
     */
    id: string;
    /**
     * The name of the commentary.
     * @type {string}
     * @memberof ApiCommentary
     */
    name: string;
    /**
     * The website for the commentary.
     * @type {string}
     * @memberof ApiCommentary
     */
    website: string;
    /**
     * The URL that the license for the commentary can be found.
     * @type {string}
     * @memberof ApiCommentary
     */
    licenseUrl: string;
    /**
     * The API-added notes for the license.
     * @type {string}
     * @memberof ApiCommentary
     */
    licenseNotes?: string | null;
    /**
     * The English name for the commentary.
     * @type {string}
     * @memberof ApiCommentary
     */
    englishName: string;
    /**
     * The ISO 639 3-letter language tag that the translation is primarily in.
     * @type {string}
     * @memberof ApiCommentary
     */
    language: string;
    /**
     * The direction that the language is written in. `ltr` indicates that the text is written from the left side of the page to the right. `rtl` indicates that the text is written from the right side of the page to the left.
     * @type {ApiCommentaryTextDirectionEnum}
     * @memberof ApiCommentary
     */
    textDirection: ApiCommentaryTextDirectionEnum;
    /**
     * The API link for the list of books for this commentary. Relative to the API origin.
     * @type {string}
     * @memberof ApiCommentary
     */
    listOfBooksApiLink: string;
    /**
     * The API link for the list of profiles for this commentary. Relative to the API origin.
     * @type {string}
     * @memberof ApiCommentary
     */
    listOfProfilesApiLink: string;
    /**
     * 
     * @type {Array<ApiCommentaryAvailableFormatsEnum>}
     * @memberof ApiCommentary
     */
    availableFormats: Array<ApiCommentaryAvailableFormatsEnum>;
    /**
     * The number of books that are contained in this commentary. Complete commentaries should have the same number of books as the Bible (66).
     * @type {number}
     * @memberof ApiCommentary
     */
    numberOfBooks: number;
    /**
     * The total number of chapters that are contained in this commentary. Complete commentaries should have the same number of chapters as the Bible (1,189).
     * @type {number}
     * @memberof ApiCommentary
     */
    totalNumberOfChapters: number;
    /**
     * The total number of verses that are contained in this commentary. Complete commentaries should have the same number of verses as the Bible (around 31,102 - some commentaries exclude verses based on the aparent likelyhood of existing in the original source texts).
     * @type {number}
     * @memberof ApiCommentary
     */
    totalNumberOfVerses: number;
    /**
     * The total number of profiles that are contained in this commentary. Profiles are used to provide additional information about people and people groups that are mentioned in the Bible.
     * @type {number}
     * @memberof ApiCommentary
     */
    totalNumberOfProfiles: number;
    /**
     * Gets the name of the language that the commentary is in. Null or undefined if the name of the language is not known.
     * @type {string}
     * @memberof ApiCommentary
     */
    languageName?: string;
    /**
     * Gets the name of the language in English. Null or undefined if the language doesn't have an english name.
     * @type {string}
     * @memberof ApiCommentary
     */
    languageEnglishName?: string;
}


/**
 * @export
 */
export const ApiCommentaryTextDirectionEnum = {
    Ltr: 'ltr',
    Rtl: 'rtl'
} as const;
export type ApiCommentaryTextDirectionEnum = typeof ApiCommentaryTextDirectionEnum[keyof typeof ApiCommentaryTextDirectionEnum];

/**
 * @export
 */
export const ApiCommentaryAvailableFormatsEnum = {
    Json: 'json',
    Usfm: 'usfm'
} as const;
export type ApiCommentaryAvailableFormatsEnum = typeof ApiCommentaryAvailableFormatsEnum[keyof typeof ApiCommentaryAvailableFormatsEnum];


/**
 * Check if a given object implements the ApiCommentary interface.
 */
export function instanceOfApiCommentary(value: object): value is ApiCommentary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('website' in value) || value['website'] === undefined) return false;
    if (!('licenseUrl' in value) || value['licenseUrl'] === undefined) return false;
    if (!('englishName' in value) || value['englishName'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('textDirection' in value) || value['textDirection'] === undefined) return false;
    if (!('listOfBooksApiLink' in value) || value['listOfBooksApiLink'] === undefined) return false;
    if (!('listOfProfilesApiLink' in value) || value['listOfProfilesApiLink'] === undefined) return false;
    if (!('availableFormats' in value) || value['availableFormats'] === undefined) return false;
    if (!('numberOfBooks' in value) || value['numberOfBooks'] === undefined) return false;
    if (!('totalNumberOfChapters' in value) || value['totalNumberOfChapters'] === undefined) return false;
    if (!('totalNumberOfVerses' in value) || value['totalNumberOfVerses'] === undefined) return false;
    if (!('totalNumberOfProfiles' in value) || value['totalNumberOfProfiles'] === undefined) return false;
    return true;
}

export function ApiCommentaryFromJSON(json: any): ApiCommentary {
    return ApiCommentaryFromJSONTyped(json, false);
}

export function ApiCommentaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCommentary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'website': json['website'],
        'licenseUrl': json['licenseUrl'],
        'licenseNotes': json['licenseNotes'] == null ? undefined : json['licenseNotes'],
        'englishName': json['englishName'],
        'language': json['language'],
        'textDirection': json['textDirection'],
        'listOfBooksApiLink': json['listOfBooksApiLink'],
        'listOfProfilesApiLink': json['listOfProfilesApiLink'],
        'availableFormats': json['availableFormats'],
        'numberOfBooks': json['numberOfBooks'],
        'totalNumberOfChapters': json['totalNumberOfChapters'],
        'totalNumberOfVerses': json['totalNumberOfVerses'],
        'totalNumberOfProfiles': json['totalNumberOfProfiles'],
        'languageName': json['languageName'] == null ? undefined : json['languageName'],
        'languageEnglishName': json['languageEnglishName'] == null ? undefined : json['languageEnglishName'],
    };
}

export function ApiCommentaryToJSON(json: any): ApiCommentary {
    return ApiCommentaryToJSONTyped(json, false);
}

export function ApiCommentaryToJSONTyped(value?: ApiCommentary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'website': value['website'],
        'licenseUrl': value['licenseUrl'],
        'licenseNotes': value['licenseNotes'],
        'englishName': value['englishName'],
        'language': value['language'],
        'textDirection': value['textDirection'],
        'listOfBooksApiLink': value['listOfBooksApiLink'],
        'listOfProfilesApiLink': value['listOfProfilesApiLink'],
        'availableFormats': value['availableFormats'],
        'numberOfBooks': value['numberOfBooks'],
        'totalNumberOfChapters': value['totalNumberOfChapters'],
        'totalNumberOfVerses': value['totalNumberOfVerses'],
        'totalNumberOfProfiles': value['totalNumberOfProfiles'],
        'languageName': value['languageName'],
        'languageEnglishName': value['languageEnglishName'],
    };
}

