/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiCommentary } from './ApiCommentary';
import {
    ApiCommentaryFromJSON,
    ApiCommentaryFromJSONTyped,
    ApiCommentaryToJSON,
    ApiCommentaryToJSONTyped,
} from './ApiCommentary';
import type { ApiCommentaryBook } from './ApiCommentaryBook';
import {
    ApiCommentaryBookFromJSON,
    ApiCommentaryBookFromJSONTyped,
    ApiCommentaryBookToJSON,
    ApiCommentaryBookToJSONTyped,
} from './ApiCommentaryBook';

/**
 * Defines an interface that contains information about the books that are available for a commentary.
 * @export
 * @interface ApiCommentaryBooks
 */
export interface ApiCommentaryBooks {
    /**
     * The commentary information for the books.
     * @type {ApiCommentary}
     * @memberof ApiCommentaryBooks
     */
    commentary: ApiCommentary;
    /**
     * The list of books that are available for the commentary.
     * @type {Array<ApiCommentaryBook>}
     * @memberof ApiCommentaryBooks
     */
    books: Array<ApiCommentaryBook>;
}

/**
 * Check if a given object implements the ApiCommentaryBooks interface.
 */
export function instanceOfApiCommentaryBooks(value: object): value is ApiCommentaryBooks {
    if (!('commentary' in value) || value['commentary'] === undefined) return false;
    if (!('books' in value) || value['books'] === undefined) return false;
    return true;
}

export function ApiCommentaryBooksFromJSON(json: any): ApiCommentaryBooks {
    return ApiCommentaryBooksFromJSONTyped(json, false);
}

export function ApiCommentaryBooksFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCommentaryBooks {
    if (json == null) {
        return json;
    }
    return {
        
        'commentary': ApiCommentaryFromJSON(json['commentary']),
        'books': ((json['books'] as Array<any>).map(ApiCommentaryBookFromJSON)),
    };
}

export function ApiCommentaryBooksToJSON(json: any): ApiCommentaryBooks {
    return ApiCommentaryBooksToJSONTyped(json, false);
}

export function ApiCommentaryBooksToJSONTyped(value?: ApiCommentaryBooks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'commentary': ApiCommentaryToJSON(value['commentary']),
        'books': ((value['books'] as Array<any>).map(ApiCommentaryBookToJSON)),
    };
}

