/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChapterVerse } from './ChapterVerse';
import {
    ChapterVerseFromJSON,
    ChapterVerseFromJSONTyped,
    ChapterVerseToJSON,
    ChapterVerseToJSONTyped,
} from './ChapterVerse';

/**
 * The information for the chapter.
 * @export
 * @interface ApiCommentaryBookChapterChapter
 */
export interface ApiCommentaryBookChapterChapter {
    /**
     * The number of the chapter.
     * @type {number}
     * @memberof ApiCommentaryBookChapterChapter
     */
    number: number;
    /**
     * The introduction that the commentary provided to the chapter. Not all commentaries provide an introduction to a chapter.
     * @type {string}
     * @memberof ApiCommentaryBookChapterChapter
     */
    introduction?: string;
    /**
     * The content of the chapter.
     * @type {Array<ChapterVerse>}
     * @memberof ApiCommentaryBookChapterChapter
     */
    content: Array<ChapterVerse>;
}

/**
 * Check if a given object implements the ApiCommentaryBookChapterChapter interface.
 */
export function instanceOfApiCommentaryBookChapterChapter(value: object): value is ApiCommentaryBookChapterChapter {
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function ApiCommentaryBookChapterChapterFromJSON(json: any): ApiCommentaryBookChapterChapter {
    return ApiCommentaryBookChapterChapterFromJSONTyped(json, false);
}

export function ApiCommentaryBookChapterChapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCommentaryBookChapterChapter {
    if (json == null) {
        return json;
    }
    return {
        
        'number': json['number'],
        'introduction': json['introduction'] == null ? undefined : json['introduction'],
        'content': ((json['content'] as Array<any>).map(ChapterVerseFromJSON)),
    };
}

export function ApiCommentaryBookChapterChapterToJSON(json: any): ApiCommentaryBookChapterChapter {
    return ApiCommentaryBookChapterChapterToJSONTyped(json, false);
}

export function ApiCommentaryBookChapterChapterToJSONTyped(value?: ApiCommentaryBookChapterChapter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'number': value['number'],
        'introduction': value['introduction'],
        'content': ((value['content'] as Array<any>).map(ChapterVerseToJSON)),
    };
}

