/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiCommentary } from './ApiCommentary';
import {
    ApiCommentaryFromJSON,
    ApiCommentaryFromJSONTyped,
    ApiCommentaryToJSON,
    ApiCommentaryToJSONTyped,
} from './ApiCommentary';
import type { ApiCommentaryBook } from './ApiCommentaryBook';
import {
    ApiCommentaryBookFromJSON,
    ApiCommentaryBookFromJSONTyped,
    ApiCommentaryBookToJSON,
    ApiCommentaryBookToJSONTyped,
} from './ApiCommentaryBook';
import type { ApiCommentaryBookChapterChapter } from './ApiCommentaryBookChapterChapter';
import {
    ApiCommentaryBookChapterChapterFromJSON,
    ApiCommentaryBookChapterChapterFromJSONTyped,
    ApiCommentaryBookChapterChapterToJSON,
    ApiCommentaryBookChapterChapterToJSONTyped,
} from './ApiCommentaryBookChapterChapter';

/**
 * Defines a schema that contains information about a book chapter in a commentary.
 * @export
 * @interface ApiCommentaryBookChapter
 */
export interface ApiCommentaryBookChapter {
    /**
     * 
     * @type {ApiCommentaryBookChapterChapter}
     * @memberof ApiCommentaryBookChapter
     */
    chapter: ApiCommentaryBookChapterChapter;
    /**
     * The commentary information for the book chapter.
     * @type {ApiCommentary}
     * @memberof ApiCommentaryBookChapter
     */
    commentary: ApiCommentary;
    /**
     * The book information for the book chapter.
     * @type {ApiCommentaryBook}
     * @memberof ApiCommentaryBookChapter
     */
    book: ApiCommentaryBook;
    /**
     * The API link for this chapter. Relative to the API origin.
     * @type {string}
     * @memberof ApiCommentaryBookChapter
     */
    thisChapterLink: string;
    /**
     * The API link to the next chapter. Relative to the API origin. Null if this is the last chapter in the commentary.
     * @type {string}
     * @memberof ApiCommentaryBookChapter
     */
    nextChapterApiLink: string | null;
    /**
     * The API link to the previous chapter. Relative to the API origin. Null if this is the first chapter in the commentary.
     * @type {string}
     * @memberof ApiCommentaryBookChapter
     */
    previousChapterApiLink: string | null;
    /**
     * The number of verses that the chapter contains.
     * @type {number}
     * @memberof ApiCommentaryBookChapter
     */
    numberOfVerses: number;
}

/**
 * Check if a given object implements the ApiCommentaryBookChapter interface.
 */
export function instanceOfApiCommentaryBookChapter(value: object): value is ApiCommentaryBookChapter {
    if (!('chapter' in value) || value['chapter'] === undefined) return false;
    if (!('commentary' in value) || value['commentary'] === undefined) return false;
    if (!('book' in value) || value['book'] === undefined) return false;
    if (!('thisChapterLink' in value) || value['thisChapterLink'] === undefined) return false;
    if (!('nextChapterApiLink' in value) || value['nextChapterApiLink'] === undefined) return false;
    if (!('previousChapterApiLink' in value) || value['previousChapterApiLink'] === undefined) return false;
    if (!('numberOfVerses' in value) || value['numberOfVerses'] === undefined) return false;
    return true;
}

export function ApiCommentaryBookChapterFromJSON(json: any): ApiCommentaryBookChapter {
    return ApiCommentaryBookChapterFromJSONTyped(json, false);
}

export function ApiCommentaryBookChapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiCommentaryBookChapter {
    if (json == null) {
        return json;
    }
    return {
        
        'chapter': ApiCommentaryBookChapterChapterFromJSON(json['chapter']),
        'commentary': ApiCommentaryFromJSON(json['commentary']),
        'book': ApiCommentaryBookFromJSON(json['book']),
        'thisChapterLink': json['thisChapterLink'],
        'nextChapterApiLink': json['nextChapterApiLink'],
        'previousChapterApiLink': json['previousChapterApiLink'],
        'numberOfVerses': json['numberOfVerses'],
    };
}

export function ApiCommentaryBookChapterToJSON(json: any): ApiCommentaryBookChapter {
    return ApiCommentaryBookChapterToJSONTyped(json, false);
}

export function ApiCommentaryBookChapterToJSONTyped(value?: ApiCommentaryBookChapter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapter': ApiCommentaryBookChapterChapterToJSON(value['chapter']),
        'commentary': ApiCommentaryToJSON(value['commentary']),
        'book': ApiCommentaryBookToJSON(value['book']),
        'thisChapterLink': value['thisChapterLink'],
        'nextChapterApiLink': value['nextChapterApiLink'],
        'previousChapterApiLink': value['previousChapterApiLink'],
        'numberOfVerses': value['numberOfVerses'],
    };
}

