/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiDataset } from './ApiDataset';
import {
    ApiDatasetFromJSON,
    ApiDatasetFromJSONTyped,
    ApiDatasetToJSON,
    ApiDatasetToJSONTyped,
} from './ApiDataset';
import type { DatasetChapterReference } from './DatasetChapterReference';
import {
    DatasetChapterReferenceFromJSON,
    DatasetChapterReferenceFromJSONTyped,
    DatasetChapterReferenceToJSON,
    DatasetChapterReferenceToJSONTyped,
} from './DatasetChapterReference';
import type { ApiDatasetBook } from './ApiDatasetBook';
import {
    ApiDatasetBookFromJSON,
    ApiDatasetBookFromJSONTyped,
    ApiDatasetBookToJSON,
    ApiDatasetBookToJSONTyped,
} from './ApiDatasetBook';
import type { DatasetChapterData } from './DatasetChapterData';
import {
    DatasetChapterDataFromJSON,
    DatasetChapterDataFromJSONTyped,
    DatasetChapterDataToJSON,
    DatasetChapterDataToJSONTyped,
} from './DatasetChapterData';

/**
 * Defines a schema that contains information about a book chapter in a dataset.
 * @export
 * @interface ApiDatasetBookChapter
 */
export interface ApiDatasetBookChapter {
    /**
     * The data for the chapter.
     * @type {DatasetChapterData}
     * @memberof ApiDatasetBookChapter
     */
    chapter: DatasetChapterData;
    /**
     * The dataset information for the book chapter.
     * @type {ApiDataset}
     * @memberof ApiDatasetBookChapter
     */
    dataset: ApiDataset;
    /**
     * The book information for the book chapter.
     * @type {ApiDatasetBook}
     * @memberof ApiDatasetBookChapter
     */
    book: ApiDatasetBook;
    /**
     * The API link for this chapter. Relative to the API origin.
     * @type {string}
     * @memberof ApiDatasetBookChapter
     */
    thisChapterLink: string;
    /**
     *
     * @type {DatasetChapterReference}
     * @memberof ApiDatasetBookChapter
     */
    thisChapterReference: DatasetChapterReference;
    /**
     * The API link to the next chapter. Relative to the API origin. Null if this is the last chapter in the dataset.
     * @type {string}
     * @memberof ApiDatasetBookChapter
     */
    nextChapterApiLink: string | null;
    /**
     * The reference for the next chapter. Null if this is the last chapter in the dataset.
     * @type {DatasetChapterReference}
     * @memberof ApiDatasetBookChapter
     */
    nextChapterReference: DatasetChapterReference | null;
    /**
     * The API link to the previous chapter. Relative to the API origin. Null if this is the first chapter in the dataset.
     * @type {string}
     * @memberof ApiDatasetBookChapter
     */
    previousChapterApiLink: string | null;
    /**
     * The reference for the previous chapter. Null if this is the first chapter in the dataset.
     * @type {DatasetChapterReference}
     * @memberof ApiDatasetBookChapter
     */
    previousChapterReference: DatasetChapterReference | null;
    /**
     * The number of verses that the chapter contains.
     * @type {number}
     * @memberof ApiDatasetBookChapter
     */
    numberOfVerses: number;
    /**
     * The number of references that the chapter contains.
     * @type {number}
     * @memberof ApiDatasetBookChapter
     */
    numberOfReferences: number;
}

/**
 * Check if a given object implements the ApiDatasetBookChapter interface.
 */
export function instanceOfApiDatasetBookChapter(
    value: object
): value is ApiDatasetBookChapter {
    if (!('chapter' in value) || value['chapter'] === undefined) return false;
    if (!('dataset' in value) || value['dataset'] === undefined) return false;
    if (!('book' in value) || value['book'] === undefined) return false;
    if (!('thisChapterLink' in value) || value['thisChapterLink'] === undefined)
        return false;
    if (
        !('thisChapterReference' in value) ||
        value['thisChapterReference'] === undefined
    )
        return false;
    if (
        !('nextChapterApiLink' in value) ||
        value['nextChapterApiLink'] === undefined
    )
        return false;
    if (
        !('nextChapterReference' in value) ||
        value['nextChapterReference'] === undefined
    )
        return false;
    if (
        !('previousChapterApiLink' in value) ||
        value['previousChapterApiLink'] === undefined
    )
        return false;
    if (
        !('previousChapterReference' in value) ||
        value['previousChapterReference'] === undefined
    )
        return false;
    if (!('numberOfVerses' in value) || value['numberOfVerses'] === undefined)
        return false;
    if (
        !('numberOfReferences' in value) ||
        value['numberOfReferences'] === undefined
    )
        return false;
    return true;
}

export function ApiDatasetBookChapterFromJSON(
    json: any
): ApiDatasetBookChapter {
    return ApiDatasetBookChapterFromJSONTyped(json, false);
}

export function ApiDatasetBookChapterFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): ApiDatasetBookChapter {
    if (json == null) {
        return json;
    }
    return {
        chapter: DatasetChapterDataFromJSON(json['chapter']),
        dataset: ApiDatasetFromJSON(json['dataset']),
        book: ApiDatasetBookFromJSON(json['book']),
        thisChapterLink: json['thisChapterLink'],
        thisChapterReference: DatasetChapterReferenceFromJSON(
            json['thisChapterReference']
        ),
        nextChapterApiLink: json['nextChapterApiLink'],
        nextChapterReference: DatasetChapterReferenceFromJSON(
            json['nextChapterReference']
        ),
        previousChapterApiLink: json['previousChapterApiLink'],
        previousChapterReference: DatasetChapterReferenceFromJSON(
            json['previousChapterReference']
        ),
        numberOfVerses: json['numberOfVerses'],
        numberOfReferences: json['numberOfReferences'],
    };
}

export function ApiDatasetBookChapterToJSON(json: any): ApiDatasetBookChapter {
    return ApiDatasetBookChapterToJSONTyped(json, false);
}

export function ApiDatasetBookChapterToJSONTyped(
    value?: ApiDatasetBookChapter | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        chapter: DatasetChapterDataToJSON(value['chapter']),
        dataset: ApiDatasetToJSON(value['dataset']),
        book: ApiDatasetBookToJSON(value['book']),
        thisChapterLink: value['thisChapterLink'],
        thisChapterReference: DatasetChapterReferenceToJSON(
            value['thisChapterReference']
        ),
        nextChapterApiLink: value['nextChapterApiLink'],
        nextChapterReference: DatasetChapterReferenceToJSON(
            value['nextChapterReference']
        ),
        previousChapterApiLink: value['previousChapterApiLink'],
        previousChapterReference: DatasetChapterReferenceToJSON(
            value['previousChapterReference']
        ),
        numberOfVerses: value['numberOfVerses'],
        numberOfReferences: value['numberOfReferences'],
    };
}
