/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookId } from './BookId';
import {
    BookIdFromJSON,
    BookIdFromJSONTyped,
    BookIdToJSON,
    BookIdToJSONTyped,
} from './BookId';
import type { DatasetChapterReference } from './DatasetChapterReference';
import {
    DatasetChapterReferenceFromJSON,
    DatasetChapterReferenceFromJSONTyped,
    DatasetChapterReferenceToJSON,
    DatasetChapterReferenceToJSONTyped,
} from './DatasetChapterReference';

/**
 * Defines a schema that contains information about a book in a dataset.
 * @export
 * @interface ApiDatasetBook
 */
export interface ApiDatasetBook {
    /**
     *
     * @type {BookId}
     * @memberof ApiDatasetBook
     */
    id: BookId;
    /**
     * The order of the book in the Bible.
     * @type {number}
     * @memberof ApiDatasetBook
     */
    order: number;
    /**
     * The number of the first chapter in the book.
     * @type {number}
     * @memberof ApiDatasetBook
     */
    firstChapterNumber: number;
    /**
     * The link to the first chapter of the book.
     * @type {string}
     * @memberof ApiDatasetBook
     */
    firstChapterApiLink: string;
    /**
     *
     * @type {DatasetChapterReference}
     * @memberof ApiDatasetBook
     */
    firstChapterReference: DatasetChapterReference;
    /**
     * The number of the last chapter in the book.
     * @type {number}
     * @memberof ApiDatasetBook
     */
    lastChapterNumber: number;
    /**
     * The link to the last chapter of the book.
     * @type {string}
     * @memberof ApiDatasetBook
     */
    lastChapterApiLink: string;
    /**
     *
     * @type {DatasetChapterReference}
     * @memberof ApiDatasetBook
     */
    lastChapterReference: DatasetChapterReference;
    /**
     * The number of chapters that the book contains.
     * @type {number}
     * @memberof ApiDatasetBook
     */
    numberOfChapters: number;
    /**
     * The number of verses that the book contains.
     * @type {number}
     * @memberof ApiDatasetBook
     */
    totalNumberOfVerses: number;
    /**
     * The number of references that the book contains.
     * @type {number}
     * @memberof ApiDatasetBook
     */
    totalNumberOfReferences: number;
}

/**
 * Check if a given object implements the ApiDatasetBook interface.
 */
export function instanceOfApiDatasetBook(
    value: object
): value is ApiDatasetBook {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    if (
        !('firstChapterNumber' in value) ||
        value['firstChapterNumber'] === undefined
    )
        return false;
    if (
        !('firstChapterApiLink' in value) ||
        value['firstChapterApiLink'] === undefined
    )
        return false;
    if (
        !('firstChapterReference' in value) ||
        value['firstChapterReference'] === undefined
    )
        return false;
    if (
        !('lastChapterNumber' in value) ||
        value['lastChapterNumber'] === undefined
    )
        return false;
    if (
        !('lastChapterApiLink' in value) ||
        value['lastChapterApiLink'] === undefined
    )
        return false;
    if (
        !('lastChapterReference' in value) ||
        value['lastChapterReference'] === undefined
    )
        return false;
    if (
        !('numberOfChapters' in value) ||
        value['numberOfChapters'] === undefined
    )
        return false;
    if (
        !('totalNumberOfVerses' in value) ||
        value['totalNumberOfVerses'] === undefined
    )
        return false;
    if (
        !('totalNumberOfReferences' in value) ||
        value['totalNumberOfReferences'] === undefined
    )
        return false;
    return true;
}

export function ApiDatasetBookFromJSON(json: any): ApiDatasetBook {
    return ApiDatasetBookFromJSONTyped(json, false);
}

export function ApiDatasetBookFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): ApiDatasetBook {
    if (json == null) {
        return json;
    }
    return {
        id: BookIdFromJSON(json['id']),
        order: json['order'],
        firstChapterNumber: json['firstChapterNumber'],
        firstChapterApiLink: json['firstChapterApiLink'],
        firstChapterReference: DatasetChapterReferenceFromJSON(
            json['firstChapterReference']
        ),
        lastChapterNumber: json['lastChapterNumber'],
        lastChapterApiLink: json['lastChapterApiLink'],
        lastChapterReference: DatasetChapterReferenceFromJSON(
            json['lastChapterReference']
        ),
        numberOfChapters: json['numberOfChapters'],
        totalNumberOfVerses: json['totalNumberOfVerses'],
        totalNumberOfReferences: json['totalNumberOfReferences'],
    };
}

export function ApiDatasetBookToJSON(json: any): ApiDatasetBook {
    return ApiDatasetBookToJSONTyped(json, false);
}

export function ApiDatasetBookToJSONTyped(
    value?: ApiDatasetBook | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        id: BookIdToJSON(value['id']),
        order: value['order'],
        firstChapterNumber: value['firstChapterNumber'],
        firstChapterApiLink: value['firstChapterApiLink'],
        firstChapterReference: DatasetChapterReferenceToJSON(
            value['firstChapterReference']
        ),
        lastChapterNumber: value['lastChapterNumber'],
        lastChapterApiLink: value['lastChapterApiLink'],
        lastChapterReference: DatasetChapterReferenceToJSON(
            value['lastChapterReference']
        ),
        numberOfChapters: value['numberOfChapters'],
        totalNumberOfVerses: value['totalNumberOfVerses'],
        totalNumberOfReferences: value['totalNumberOfReferences'],
    };
}
