/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiDataset } from './ApiDataset';
import {
    ApiDatasetFromJSON,
    ApiDatasetFromJSONTyped,
    ApiDatasetToJSON,
    ApiDatasetToJSONTyped,
} from './ApiDataset';
import type { ApiDatasetBook } from './ApiDatasetBook';
import {
    ApiDatasetBookFromJSON,
    ApiDatasetBookFromJSONTyped,
    ApiDatasetBookToJSON,
    ApiDatasetBookToJSONTyped,
} from './ApiDatasetBook';

/**
 * Defines an interface that contains information about the books that are available for a dataset.
 * @export
 * @interface ApiDatasetBooks
 */
export interface ApiDatasetBooks {
    /**
     * The dataset information for the books.
     * @type {ApiDataset}
     * @memberof ApiDatasetBooks
     */
    dataset: ApiDataset;
    /**
     * The list of books that are available for the dataset.
     * @type {Array<ApiDatasetBook>}
     * @memberof ApiDatasetBooks
     */
    books: Array<ApiDatasetBook>;
}

/**
 * Check if a given object implements the ApiDatasetBooks interface.
 */
export function instanceOfApiDatasetBooks(value: object): value is ApiDatasetBooks {
    if (!('dataset' in value) || value['dataset'] === undefined) return false;
    if (!('books' in value) || value['books'] === undefined) return false;
    return true;
}

export function ApiDatasetBooksFromJSON(json: any): ApiDatasetBooks {
    return ApiDatasetBooksFromJSONTyped(json, false);
}

export function ApiDatasetBooksFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDatasetBooks {
    if (json == null) {
        return json;
    }
    return {
        
        'dataset': ApiDatasetFromJSON(json['dataset']),
        'books': ((json['books'] as Array<any>).map(ApiDatasetBookFromJSON)),
    };
}

export function ApiDatasetBooksToJSON(json: any): ApiDatasetBooks {
    return ApiDatasetBooksToJSONTyped(json, false);
}

export function ApiDatasetBooksToJSONTyped(value?: ApiDatasetBooks | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dataset': ApiDatasetToJSON(value['dataset']),
        'books': ((value['books'] as Array<any>).map(ApiDatasetBookToJSON)),
    };
}

