/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TranslationChapterReference } from './TranslationChapterReference';
import {
    TranslationChapterReferenceFromJSON,
    TranslationChapterReferenceFromJSONTyped,
    TranslationChapterReferenceToJSON,
    TranslationChapterReferenceToJSONTyped,
} from './TranslationChapterReference';
import type { BookId } from './BookId';
import {
    BookIdFromJSON,
    BookIdFromJSONTyped,
    BookIdToJSON,
    BookIdToJSONTyped,
} from './BookId';

/**
 * Defines a schema that contains information about a translation book.
 * @export
 * @interface ApiTranslationBook
 */
export interface ApiTranslationBook {
    /**
     *
     * @type {BookId}
     * @memberof ApiTranslationBook
     */
    id: BookId;
    /**
     * The name that the translation provided for the book.
     * @type {string}
     * @memberof ApiTranslationBook
     */
    name: string;
    /**
     * The common name for the book.
     * @type {string}
     * @memberof ApiTranslationBook
     */
    commonName: string;
    /**
     * The title of the book. This is usually a more descriptive version of the book name. If not available, then one was not provided by the translation.
     * @type {string}
     * @memberof ApiTranslationBook
     */
    title: string | null;
    /**
     * The numerical order of the book in the translation.
     * @type {number}
     * @memberof ApiTranslationBook
     */
    order: number;
    /**
     * Whether the book is an apocryphal book.
     * @type {boolean}
     * @memberof ApiTranslationBook
     */
    isApocryphal?: boolean;
    /**
     * The number of the first chapter in the book.
     * @type {number}
     * @memberof ApiTranslationBook
     */
    firstChapterNumber: number;
    /**
     * The link to the first chapter of the book.
     * @type {string}
     * @memberof ApiTranslationBook
     */
    firstChapterApiLink: string;
    /**
     *
     * @type {TranslationChapterReference}
     * @memberof ApiTranslationBook
     */
    firstChapterReference: TranslationChapterReference;
    /**
     * The number of the last chapter in the book.
     * @type {number}
     * @memberof ApiTranslationBook
     */
    lastChapterNumber: number;
    /**
     * The link to the last chapter of the book.
     * @type {string}
     * @memberof ApiTranslationBook
     */
    lastChapterApiLink: string;
    /**
     *
     * @type {TranslationChapterReference}
     * @memberof ApiTranslationBook
     */
    lastChapterReference: TranslationChapterReference;
    /**
     * The number of chapters that the book contains.
     * @type {number}
     * @memberof ApiTranslationBook
     */
    numberOfChapters: number;
    /**
     * The number of verses that the book contains.
     * @type {number}
     * @memberof ApiTranslationBook
     */
    totalNumberOfVerses: number;
}

/**
 * Check if a given object implements the ApiTranslationBook interface.
 */
export function instanceOfApiTranslationBook(
    value: object
): value is ApiTranslationBook {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('commonName' in value) || value['commonName'] === undefined)
        return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    if (
        !('firstChapterNumber' in value) ||
        value['firstChapterNumber'] === undefined
    )
        return false;
    if (
        !('firstChapterApiLink' in value) ||
        value['firstChapterApiLink'] === undefined
    )
        return false;
    if (
        !('firstChapterReference' in value) ||
        value['firstChapterReference'] === undefined
    )
        return false;
    if (
        !('lastChapterNumber' in value) ||
        value['lastChapterNumber'] === undefined
    )
        return false;
    if (
        !('lastChapterApiLink' in value) ||
        value['lastChapterApiLink'] === undefined
    )
        return false;
    if (
        !('lastChapterReference' in value) ||
        value['lastChapterReference'] === undefined
    )
        return false;
    if (
        !('numberOfChapters' in value) ||
        value['numberOfChapters'] === undefined
    )
        return false;
    if (
        !('totalNumberOfVerses' in value) ||
        value['totalNumberOfVerses'] === undefined
    )
        return false;
    return true;
}

export function ApiTranslationBookFromJSON(json: any): ApiTranslationBook {
    return ApiTranslationBookFromJSONTyped(json, false);
}

export function ApiTranslationBookFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): ApiTranslationBook {
    if (json == null) {
        return json;
    }
    return {
        id: BookIdFromJSON(json['id']),
        name: json['name'],
        commonName: json['commonName'],
        title: json['title'],
        order: json['order'],
        isApocryphal:
            json['isApocryphal'] == null ? undefined : json['isApocryphal'],
        firstChapterNumber: json['firstChapterNumber'],
        firstChapterApiLink: json['firstChapterApiLink'],
        firstChapterReference: TranslationChapterReferenceFromJSON(
            json['firstChapterReference']
        ),
        lastChapterNumber: json['lastChapterNumber'],
        lastChapterApiLink: json['lastChapterApiLink'],
        lastChapterReference: TranslationChapterReferenceFromJSON(
            json['lastChapterReference']
        ),
        numberOfChapters: json['numberOfChapters'],
        totalNumberOfVerses: json['totalNumberOfVerses'],
    };
}

export function ApiTranslationBookToJSON(json: any): ApiTranslationBook {
    return ApiTranslationBookToJSONTyped(json, false);
}

export function ApiTranslationBookToJSONTyped(
    value?: ApiTranslationBook | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        id: BookIdToJSON(value['id']),
        name: value['name'],
        commonName: value['commonName'],
        title: value['title'],
        order: value['order'],
        isApocryphal: value['isApocryphal'],
        firstChapterNumber: value['firstChapterNumber'],
        firstChapterApiLink: value['firstChapterApiLink'],
        firstChapterReference: TranslationChapterReferenceToJSON(
            value['firstChapterReference']
        ),
        lastChapterNumber: value['lastChapterNumber'],
        lastChapterApiLink: value['lastChapterApiLink'],
        lastChapterReference: TranslationChapterReferenceToJSON(
            value['lastChapterReference']
        ),
        numberOfChapters: value['numberOfChapters'],
        totalNumberOfVerses: value['totalNumberOfVerses'],
    };
}
