/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TranslationBookChapter } from './TranslationBookChapter';
import {
    TranslationBookChapterFromJSON,
    TranslationBookChapterFromJSONTyped,
    TranslationBookChapterToJSON,
    TranslationBookChapterToJSONTyped,
} from './TranslationBookChapter';
import type { BookId } from './BookId';
import {
    BookIdFromJSON,
    BookIdFromJSONTyped,
    BookIdToJSON,
    BookIdToJSONTyped,
} from './BookId';

/**
 * A book in the complete translation download.
 * @export
 * @interface ApiTranslationCompleteBook
 */
export interface ApiTranslationCompleteBook {
    /**
     * 
     * @type {BookId}
     * @memberof ApiTranslationCompleteBook
     */
    id: BookId;
    /**
     * The name that the translation provided for the book.
     * @type {string}
     * @memberof ApiTranslationCompleteBook
     */
    name: string;
    /**
     * The common name for the book.
     * @type {string}
     * @memberof ApiTranslationCompleteBook
     */
    commonName: string;
    /**
     * The title of the book. This is usually a more descriptive version of the book name. If not available, then one was not provided by the translation.
     * @type {string}
     * @memberof ApiTranslationCompleteBook
     */
    title: string | null;
    /**
     * The numerical order of the book in the translation.
     * @type {number}
     * @memberof ApiTranslationCompleteBook
     */
    order: number;
    /**
     * Whether the book is an apocryphal book.
     * @type {boolean}
     * @memberof ApiTranslationCompleteBook
     */
    isApocryphal?: boolean;
    /**
     * The number of chapters in the book.
     * @type {number}
     * @memberof ApiTranslationCompleteBook
     */
    numberOfChapters: number;
    /**
     * The total number of verses in the book.
     * @type {number}
     * @memberof ApiTranslationCompleteBook
     */
    totalNumberOfVerses: number;
    /**
     * The complete list of chapters with all content.
     * @type {Array<TranslationBookChapter>}
     * @memberof ApiTranslationCompleteBook
     */
    chapters: Array<TranslationBookChapter>;
}



/**
 * Check if a given object implements the ApiTranslationCompleteBook interface.
 */
export function instanceOfApiTranslationCompleteBook(value: object): value is ApiTranslationCompleteBook {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('commonName' in value) || value['commonName'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('order' in value) || value['order'] === undefined) return false;
    if (!('numberOfChapters' in value) || value['numberOfChapters'] === undefined) return false;
    if (!('totalNumberOfVerses' in value) || value['totalNumberOfVerses'] === undefined) return false;
    if (!('chapters' in value) || value['chapters'] === undefined) return false;
    return true;
}

export function ApiTranslationCompleteBookFromJSON(json: any): ApiTranslationCompleteBook {
    return ApiTranslationCompleteBookFromJSONTyped(json, false);
}

export function ApiTranslationCompleteBookFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTranslationCompleteBook {
    if (json == null) {
        return json;
    }
    return {
        
        'id': BookIdFromJSON(json['id']),
        'name': json['name'],
        'commonName': json['commonName'],
        'title': json['title'],
        'order': json['order'],
        'isApocryphal': json['isApocryphal'] == null ? undefined : json['isApocryphal'],
        'numberOfChapters': json['numberOfChapters'],
        'totalNumberOfVerses': json['totalNumberOfVerses'],
        'chapters': ((json['chapters'] as Array<any>).map(TranslationBookChapterFromJSON)),
    };
}

export function ApiTranslationCompleteBookToJSON(json: any): ApiTranslationCompleteBook {
    return ApiTranslationCompleteBookToJSONTyped(json, false);
}

export function ApiTranslationCompleteBookToJSONTyped(value?: ApiTranslationCompleteBook | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': BookIdToJSON(value['id']),
        'name': value['name'],
        'commonName': value['commonName'],
        'title': value['title'],
        'order': value['order'],
        'isApocryphal': value['isApocryphal'],
        'numberOfChapters': value['numberOfChapters'],
        'totalNumberOfVerses': value['totalNumberOfVerses'],
        'chapters': ((value['chapters'] as Array<any>).map(TranslationBookChapterToJSON)),
    };
}

