/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiTranslationCompleteBook } from './ApiTranslationCompleteBook';
import {
    ApiTranslationCompleteBookFromJSON,
    ApiTranslationCompleteBookFromJSONTyped,
    ApiTranslationCompleteBookToJSON,
    ApiTranslationCompleteBookToJSONTyped,
} from './ApiTranslationCompleteBook';
import type { ApiTranslation } from './ApiTranslation';
import {
    ApiTranslationFromJSON,
    ApiTranslationFromJSONTyped,
    ApiTranslationToJSON,
    ApiTranslationToJSONTyped,
} from './ApiTranslation';

/**
 * Defines the complete translation download data. Maps to the /api/:translationId/complete.json endpoint.
 * @export
 * @interface ApiTranslationComplete
 */
export interface ApiTranslationComplete {
    /**
     * The translation metadata.
     * @type {ApiTranslation}
     * @memberof ApiTranslationComplete
     */
    translation: ApiTranslation;
    /**
     * The complete list of books with all their chapters.
     * @type {Array<ApiTranslationCompleteBook>}
     * @memberof ApiTranslationComplete
     */
    books: Array<ApiTranslationCompleteBook>;
}

/**
 * Check if a given object implements the ApiTranslationComplete interface.
 */
export function instanceOfApiTranslationComplete(value: object): value is ApiTranslationComplete {
    if (!('translation' in value) || value['translation'] === undefined) return false;
    if (!('books' in value) || value['books'] === undefined) return false;
    return true;
}

export function ApiTranslationCompleteFromJSON(json: any): ApiTranslationComplete {
    return ApiTranslationCompleteFromJSONTyped(json, false);
}

export function ApiTranslationCompleteFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTranslationComplete {
    if (json == null) {
        return json;
    }
    return {
        
        'translation': ApiTranslationFromJSON(json['translation']),
        'books': ((json['books'] as Array<any>).map(ApiTranslationCompleteBookFromJSON)),
    };
}

export function ApiTranslationCompleteToJSON(json: any): ApiTranslationComplete {
    return ApiTranslationCompleteToJSONTyped(json, false);
}

export function ApiTranslationCompleteToJSONTyped(value?: ApiTranslationComplete | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'translation': ApiTranslationToJSON(value['translation']),
        'books': ((value['books'] as Array<any>).map(ApiTranslationCompleteBookToJSON)),
    };
}

