/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChapterFootnote } from './ChapterFootnote';
import {
    ChapterFootnoteFromJSON,
    ChapterFootnoteFromJSONTyped,
    ChapterFootnoteToJSON,
    ChapterFootnoteToJSONTyped,
} from './ChapterFootnote';
import type { ChapterContent } from './ChapterContent';
import {
    ChapterContentFromJSON,
    ChapterContentFromJSONTyped,
    ChapterContentToJSON,
    ChapterContentToJSONTyped,
} from './ChapterContent';

/**
 * The information for the chapter.
 * @export
 * @interface ApiTranslationBookChapterChapter
 */
export interface ApiTranslationBookChapterChapter {
    /**
     * The number of the chapter.
     * @type {number}
     * @memberof ApiTranslationBookChapterChapter
     */
    number: number;
    /**
     * The content of the chapter.
     * @type {Array<ChapterContent>}
     * @memberof ApiTranslationBookChapterChapter
     */
    content: Array<ChapterContent>;
    /**
     * The list of footnotes for the chapter.
     * @type {Array<ChapterFootnote>}
     * @memberof ApiTranslationBookChapterChapter
     */
    footnotes: Array<ChapterFootnote>;
}

/**
 * Check if a given object implements the ApiTranslationBookChapterChapter interface.
 */
export function instanceOfApiTranslationBookChapterChapter(value: object): value is ApiTranslationBookChapterChapter {
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('footnotes' in value) || value['footnotes'] === undefined) return false;
    return true;
}

export function ApiTranslationBookChapterChapterFromJSON(json: any): ApiTranslationBookChapterChapter {
    return ApiTranslationBookChapterChapterFromJSONTyped(json, false);
}

export function ApiTranslationBookChapterChapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTranslationBookChapterChapter {
    if (json == null) {
        return json;
    }
    return {
        
        'number': json['number'],
        'content': ((json['content'] as Array<any>).map(ChapterContentFromJSON)),
        'footnotes': ((json['footnotes'] as Array<any>).map(ChapterFootnoteFromJSON)),
    };
}

export function ApiTranslationBookChapterChapterToJSON(json: any): ApiTranslationBookChapterChapter {
    return ApiTranslationBookChapterChapterToJSONTyped(json, false);
}

export function ApiTranslationBookChapterChapterToJSONTyped(value?: ApiTranslationBookChapterChapter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'number': value['number'],
        'content': ((value['content'] as Array<any>).map(ChapterContentToJSON)),
        'footnotes': ((value['footnotes'] as Array<any>).map(ChapterFootnoteToJSON)),
    };
}

