/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Defines the schema for a heading in a chapter.
 * @export
 * @interface ChapterHeading
 */
export interface ChapterHeading {
    /**
     * 
     * @type {ChapterHeadingTypeEnum}
     * @memberof ChapterHeading
     */
    type: ChapterHeadingTypeEnum;
    /**
     * The content for the heading. If multiple strings are included in the array, they should be concatenated with a space.
     * @type {Array<string>}
     * @memberof ChapterHeading
     */
    content: Array<string>;
}


/**
 * @export
 */
export const ChapterHeadingTypeEnum = {
    Heading: 'heading'
} as const;
export type ChapterHeadingTypeEnum = typeof ChapterHeadingTypeEnum[keyof typeof ChapterHeadingTypeEnum];


/**
 * Check if a given object implements the ChapterHeading interface.
 */
export function instanceOfChapterHeading(value: object): value is ChapterHeading {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function ChapterHeadingFromJSON(json: any): ChapterHeading {
    return ChapterHeadingFromJSONTyped(json, false);
}

export function ChapterHeadingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterHeading {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'content': json['content'],
    };
}

export function ChapterHeadingToJSON(json: any): ChapterHeading {
    return ChapterHeadingToJSONTyped(json, false);
}

export function ChapterHeadingToJSONTyped(value?: ChapterHeading | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'content': value['content'],
    };
}

