/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The caller that should be used for the footnote. For footnotes, a "caller" is the character that is used in the text to reference to footnote. For example, in the text: Hello (a) World ---- (a) This is a footnote. The "(a)" is the caller. If "+", then the caller should be autogenerated. If null, then the caller should be empty. If a string, then the caller should be that string.
 * @export
 * @interface ChapterFootnoteCaller
 */
export interface ChapterFootnoteCaller {
}

/**
 * Check if a given object implements the ChapterFootnoteCaller interface.
 */
export function instanceOfChapterFootnoteCaller(value: object): value is ChapterFootnoteCaller {
    return true;
}

export function ChapterFootnoteCallerFromJSON(json: any): ChapterFootnoteCaller {
    return ChapterFootnoteCallerFromJSONTyped(json, false);
}

export function ChapterFootnoteCallerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterFootnoteCaller {
    return json;
}

export function ChapterFootnoteCallerToJSON(json: any): ChapterFootnoteCaller {
    return ChapterFootnoteCallerToJSONTyped(json, false);
}

export function ChapterFootnoteCallerToJSONTyped(value?: ChapterFootnoteCaller | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

