/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InlineHeading } from './InlineHeading';
import {
    InlineHeadingFromJSON,
    InlineHeadingFromJSONTyped,
    InlineHeadingToJSON,
    InlineHeadingToJSONTyped,
} from './InlineHeading';
import type { InlineLineBreak } from './InlineLineBreak';
import {
    InlineLineBreakFromJSON,
    InlineLineBreakFromJSONTyped,
    InlineLineBreakToJSON,
    InlineLineBreakToJSONTyped,
} from './InlineLineBreak';
import type { VerseFootnoteReference } from './VerseFootnoteReference';
import {
    VerseFootnoteReferenceFromJSON,
    VerseFootnoteReferenceFromJSONTyped,
    VerseFootnoteReferenceToJSON,
    VerseFootnoteReferenceToJSONTyped,
} from './VerseFootnoteReference';
import type { FormattedText } from './FormattedText';
import {
    FormattedTextFromJSON,
    FormattedTextFromJSONTyped,
    FormattedTextToJSON,
    FormattedTextToJSONTyped,
} from './FormattedText';

/**
 * 
 * @export
 * @interface ChapterVerseContentInner
 */
export interface ChapterVerseContentInner {
    /**
     * The text that is formatted.
     * @type {string}
     * @memberof ChapterVerseContentInner
     */
    text: string;
    /**
     * Whether the text represents a poem. The number indicates the level of indent. Common in Psalms.
     * @type {number}
     * @memberof ChapterVerseContentInner
     */
    poem?: number;
    /**
     * Whether the text represents the Words of Jesus.
     * @type {boolean}
     * @memberof ChapterVerseContentInner
     */
    wordsOfJesus?: boolean;
    /**
     * The text of the heading.
     * @type {string}
     * @memberof ChapterVerseContentInner
     */
    heading: string;
    /**
     * 
     * @type {ChapterVerseContentInnerLineBreakEnum}
     * @memberof ChapterVerseContentInner
     */
    lineBreak: ChapterVerseContentInnerLineBreakEnum;
    /**
     * The ID of the note.
     * @type {number}
     * @memberof ChapterVerseContentInner
     */
    noteId: number;
}


/**
 * @export
 */
export const ChapterVerseContentInnerLineBreakEnum = {
    True: true
} as const;
export type ChapterVerseContentInnerLineBreakEnum = typeof ChapterVerseContentInnerLineBreakEnum[keyof typeof ChapterVerseContentInnerLineBreakEnum];


/**
 * Check if a given object implements the ChapterVerseContentInner interface.
 */
export function instanceOfChapterVerseContentInner(value: object): value is ChapterVerseContentInner {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('heading' in value) || value['heading'] === undefined) return false;
    if (!('lineBreak' in value) || value['lineBreak'] === undefined) return false;
    if (!('noteId' in value) || value['noteId'] === undefined) return false;
    return true;
}

export function ChapterVerseContentInnerFromJSON(json: any): ChapterVerseContentInner {
    return ChapterVerseContentInnerFromJSONTyped(json, false);
}

export function ChapterVerseContentInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterVerseContentInner {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'poem': json['poem'] == null ? undefined : json['poem'],
        'wordsOfJesus': json['wordsOfJesus'] == null ? undefined : json['wordsOfJesus'],
        'heading': json['heading'],
        'lineBreak': json['lineBreak'],
        'noteId': json['noteId'],
    };
}

export function ChapterVerseContentInnerToJSON(json: any): ChapterVerseContentInner {
    return ChapterVerseContentInnerToJSONTyped(json, false);
}

export function ChapterVerseContentInnerToJSONTyped(value?: ChapterVerseContentInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'poem': value['poem'],
        'wordsOfJesus': value['wordsOfJesus'],
        'heading': value['heading'],
        'lineBreak': value['lineBreak'],
        'noteId': value['noteId'],
    };
}

