/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VerseFootnoteReference } from './VerseFootnoteReference';
import {
    VerseFootnoteReferenceFromJSON,
    VerseFootnoteReferenceFromJSONTyped,
    VerseFootnoteReferenceToJSON,
    VerseFootnoteReferenceToJSONTyped,
} from './VerseFootnoteReference';
import type { FormattedText } from './FormattedText';
import {
    FormattedTextFromJSON,
    FormattedTextFromJSONTyped,
    FormattedTextToJSON,
    FormattedTextToJSONTyped,
} from './FormattedText';

/**
 * 
 * @export
 * @interface ChapterHebrewSubtitleContentInner
 */
export interface ChapterHebrewSubtitleContentInner {
    /**
     * The text that is formatted.
     * @type {string}
     * @memberof ChapterHebrewSubtitleContentInner
     */
    text: string;
    /**
     * Whether the text represents a poem. The number indicates the level of indent. Common in Psalms.
     * @type {number}
     * @memberof ChapterHebrewSubtitleContentInner
     */
    poem?: number;
    /**
     * Whether the text represents the Words of Jesus.
     * @type {boolean}
     * @memberof ChapterHebrewSubtitleContentInner
     */
    wordsOfJesus?: boolean;
    /**
     * The ID of the note.
     * @type {number}
     * @memberof ChapterHebrewSubtitleContentInner
     */
    noteId: number;
}

/**
 * Check if a given object implements the ChapterHebrewSubtitleContentInner interface.
 */
export function instanceOfChapterHebrewSubtitleContentInner(value: object): value is ChapterHebrewSubtitleContentInner {
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('noteId' in value) || value['noteId'] === undefined) return false;
    return true;
}

export function ChapterHebrewSubtitleContentInnerFromJSON(json: any): ChapterHebrewSubtitleContentInner {
    return ChapterHebrewSubtitleContentInnerFromJSONTyped(json, false);
}

export function ChapterHebrewSubtitleContentInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChapterHebrewSubtitleContentInner {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
        'poem': json['poem'] == null ? undefined : json['poem'],
        'wordsOfJesus': json['wordsOfJesus'] == null ? undefined : json['wordsOfJesus'],
        'noteId': json['noteId'],
    };
}

export function ChapterHebrewSubtitleContentInnerToJSON(json: any): ChapterHebrewSubtitleContentInner {
    return ChapterHebrewSubtitleContentInnerToJSONTyped(json, false);
}

export function ChapterHebrewSubtitleContentInnerToJSONTyped(value?: ChapterHebrewSubtitleContentInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'poem': value['poem'],
        'wordsOfJesus': value['wordsOfJesus'],
        'noteId': value['noteId'],
    };
}

