/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookId } from './BookId';
import {
    BookIdFromJSON,
    BookIdFromJSONTyped,
    BookIdToJSON,
    BookIdToJSONTyped,
} from './BookId';

/**
 * Defines a reference to a chapter in a commentary.
 * @export
 * @interface CommentaryChapterReference
 */
export interface CommentaryChapterReference {
    /**
     * The ID of the commentary that the chapter reference is for.
     * @type {string}
     * @memberof CommentaryChapterReference
     */
    commentaryId: string;
    /**
     *
     * @type {BookId}
     * @memberof CommentaryChapterReference
     */
    book: BookId;
    /**
     * The chapter number of the chapter reference.
     * @type {number}
     * @memberof CommentaryChapterReference
     */
    chapter: number;
}

/**
 * Check if a given object implements the CommentaryChapterReference interface.
 */
export function instanceOfCommentaryChapterReference(
    value: object
): value is CommentaryChapterReference {
    if (!('commentaryId' in value) || value['commentaryId'] === undefined)
        return false;
    if (!('book' in value) || value['book'] === undefined) return false;
    if (!('chapter' in value) || value['chapter'] === undefined) return false;
    return true;
}

export function CommentaryChapterReferenceFromJSON(
    json: any
): CommentaryChapterReference {
    return CommentaryChapterReferenceFromJSONTyped(json, false);
}

export function CommentaryChapterReferenceFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): CommentaryChapterReference {
    if (json == null) {
        return json;
    }
    return {
        commentaryId: json['commentaryId'],
        book: BookIdFromJSON(json['book']),
        chapter: json['chapter'],
    };
}

export function CommentaryChapterReferenceToJSON(
    json: any
): CommentaryChapterReference {
    return CommentaryChapterReferenceToJSONTyped(json, false);
}

export function CommentaryChapterReferenceToJSONTyped(
    value?: CommentaryChapterReference | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        commentaryId: value['commentaryId'],
        book: BookIdToJSON(value['book']),
        chapter: value['chapter'],
    };
}
