/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookId } from './BookId';
import {
    BookIdFromJSON,
    BookIdFromJSONTyped,
    BookIdToJSON,
    BookIdToJSONTyped,
} from './BookId';

/**
 * Defines a reference to a chapter in a dataset.
 * @export
 * @interface DatasetChapterReference
 */
export interface DatasetChapterReference {
    /**
     * The ID of the dataset that the chapter reference is for.
     * @type {string}
     * @memberof DatasetChapterReference
     */
    datasetId: string;
    /**
     *
     * @type {BookId}
     * @memberof DatasetChapterReference
     */
    book: BookId;
    /**
     * The chapter number of the chapter reference.
     * @type {number}
     * @memberof DatasetChapterReference
     */
    chapter: number;
}

/**
 * Check if a given object implements the DatasetChapterReference interface.
 */
export function instanceOfDatasetChapterReference(
    value: object
): value is DatasetChapterReference {
    if (!('datasetId' in value) || value['datasetId'] === undefined)
        return false;
    if (!('book' in value) || value['book'] === undefined) return false;
    if (!('chapter' in value) || value['chapter'] === undefined) return false;
    return true;
}

export function DatasetChapterReferenceFromJSON(
    json: any
): DatasetChapterReference {
    return DatasetChapterReferenceFromJSONTyped(json, false);
}

export function DatasetChapterReferenceFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): DatasetChapterReference {
    if (json == null) {
        return json;
    }
    return {
        datasetId: json['datasetId'],
        book: BookIdFromJSON(json['book']),
        chapter: json['chapter'],
    };
}

export function DatasetChapterReferenceToJSON(
    json: any
): DatasetChapterReference {
    return DatasetChapterReferenceToJSONTyped(json, false);
}

export function DatasetChapterReferenceToJSONTyped(
    value?: DatasetChapterReference | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        datasetId: value['datasetId'],
        book: BookIdToJSON(value['book']),
        chapter: value['chapter'],
    };
}
