/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DatasetChapterVerseContent } from './DatasetChapterVerseContent';
import {
    DatasetChapterVerseContentFromJSON,
    DatasetChapterVerseContentFromJSONTyped,
    DatasetChapterVerseContentToJSON,
    DatasetChapterVerseContentToJSONTyped,
} from './DatasetChapterVerseContent';

/**
 * Defines the schema for information about a chapter in a dataset.
 * @export
 * @interface DatasetChapterData
 */
export interface DatasetChapterData {
    /**
     * The number of the chapter.
     * @type {number}
     * @memberof DatasetChapterData
     */
    number: number;
    /**
     * The content of the chapter.
     * @type {Array<DatasetChapterVerseContent>}
     * @memberof DatasetChapterData
     */
    content: Array<DatasetChapterVerseContent>;
}

/**
 * Check if a given object implements the DatasetChapterData interface.
 */
export function instanceOfDatasetChapterData(value: object): value is DatasetChapterData {
    if (!('number' in value) || value['number'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function DatasetChapterDataFromJSON(json: any): DatasetChapterData {
    return DatasetChapterDataFromJSONTyped(json, false);
}

export function DatasetChapterDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatasetChapterData {
    if (json == null) {
        return json;
    }
    return {
        
        'number': json['number'],
        'content': ((json['content'] as Array<any>).map(DatasetChapterVerseContentFromJSON)),
    };
}

export function DatasetChapterDataToJSON(json: any): DatasetChapterData {
    return DatasetChapterDataToJSONTyped(json, false);
}

export function DatasetChapterDataToJSONTyped(value?: DatasetChapterData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'number': value['number'],
        'content': ((value['content'] as Array<any>).map(DatasetChapterVerseContentToJSON)),
    };
}

