/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiTranslationBookChapterChapter } from './ApiTranslationBookChapterChapter';
import {
    ApiTranslationBookChapterChapterFromJSON,
    ApiTranslationBookChapterChapterFromJSONTyped,
    ApiTranslationBookChapterChapterToJSON,
    ApiTranslationBookChapterChapterToJSONTyped,
} from './ApiTranslationBookChapterChapter';

/**
 * Defines the schema for information about a book chapter.
 * @export
 * @interface TranslationBookChapter
 */
export interface TranslationBookChapter {
    /**
     * 
     * @type {ApiTranslationBookChapterChapter}
     * @memberof TranslationBookChapter
     */
    chapter: ApiTranslationBookChapterChapter;
    /**
     * The links to different audio versions for the chapter.
     * @type {{ [key: string]: string; }}
     * @memberof TranslationBookChapter
     */
    thisChapterAudioLinks: { [key: string]: string; };
}

/**
 * Check if a given object implements the TranslationBookChapter interface.
 */
export function instanceOfTranslationBookChapter(value: object): value is TranslationBookChapter {
    if (!('chapter' in value) || value['chapter'] === undefined) return false;
    if (!('thisChapterAudioLinks' in value) || value['thisChapterAudioLinks'] === undefined) return false;
    return true;
}

export function TranslationBookChapterFromJSON(json: any): TranslationBookChapter {
    return TranslationBookChapterFromJSONTyped(json, false);
}

export function TranslationBookChapterFromJSONTyped(json: any, ignoreDiscriminator: boolean): TranslationBookChapter {
    if (json == null) {
        return json;
    }
    return {
        
        'chapter': ApiTranslationBookChapterChapterFromJSON(json['chapter']),
        'thisChapterAudioLinks': json['thisChapterAudioLinks'],
    };
}

export function TranslationBookChapterToJSON(json: any): TranslationBookChapter {
    return TranslationBookChapterToJSONTyped(json, false);
}

export function TranslationBookChapterToJSONTyped(value?: TranslationBookChapter | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chapter': ApiTranslationBookChapterChapterToJSON(value['chapter']),
        'thisChapterAudioLinks': value['thisChapterAudioLinks'],
    };
}

