/* tslint:disable */
/* eslint-disable */
/**
 * Free Use Bible API
 * An API for accessing over 1000 different Bible translations.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hello@helloao.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookId } from './BookId';
import {
    BookIdFromJSON,
    BookIdFromJSONTyped,
    BookIdToJSON,
    BookIdToJSONTyped,
} from './BookId';

/**
 * Defines a reference to a chapter in a translation.
 * @export
 * @interface TranslationChapterReference
 */
export interface TranslationChapterReference {
    /**
     * The ID of the translation that the chapter reference is for.
     * @type {string}
     * @memberof TranslationChapterReference
     */
    translationId: string;
    /**
     *
     * @type {BookId}
     * @memberof TranslationChapterReference
     */
    book: BookId;
    /**
     * The chapter number of the chapter reference.
     * @type {number}
     * @memberof TranslationChapterReference
     */
    chapter: number;
}

/**
 * Check if a given object implements the TranslationChapterReference interface.
 */
export function instanceOfTranslationChapterReference(
    value: object
): value is TranslationChapterReference {
    if (!('translationId' in value) || value['translationId'] === undefined)
        return false;
    if (!('book' in value) || value['book'] === undefined) return false;
    if (!('chapter' in value) || value['chapter'] === undefined) return false;
    return true;
}

export function TranslationChapterReferenceFromJSON(
    json: any
): TranslationChapterReference {
    return TranslationChapterReferenceFromJSONTyped(json, false);
}

export function TranslationChapterReferenceFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): TranslationChapterReference {
    if (json == null) {
        return json;
    }
    return {
        translationId: json['translationId'],
        book: BookIdFromJSON(json['book']),
        chapter: json['chapter'],
    };
}

export function TranslationChapterReferenceToJSON(
    json: any
): TranslationChapterReference {
    return TranslationChapterReferenceToJSONTyped(json, false);
}

export function TranslationChapterReferenceToJSONTyped(
    value?: TranslationChapterReference | null,
    ignoreDiscriminator: boolean = false
): any {
    if (value == null) {
        return value;
    }

    return {
        translationId: value['translationId'],
        book: BookIdToJSON(value['book']),
        chapter: value['chapter'],
    };
}
