// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://bible.helloao.org' | (string & {});
};

/**
 * IDs for books. Follows the USFM standard (https://ubsicap.github.io/usfm/identification/books.html)
 */
export type BookId =
    | 'GEN'
    | 'EXO'
    | 'LEV'
    | 'NUM'
    | 'DEU'
    | 'JOS'
    | 'JDG'
    | 'RUT'
    | '1SA'
    | '2SA'
    | '1KI'
    | '2KI'
    | '1CH'
    | '2CH'
    | 'EZR'
    | 'NEH'
    | 'EST'
    | 'JOB'
    | 'PSA'
    | 'PRO'
    | 'ECC'
    | 'SNG'
    | 'ISA'
    | 'JER'
    | 'LAM'
    | 'EZK'
    | 'DAN'
    | 'HOS'
    | 'JOL'
    | 'AMO'
    | 'OBA'
    | 'JON'
    | 'MIC'
    | 'NAM'
    | 'HAB'
    | 'ZEP'
    | 'HAG'
    | 'ZEC'
    | 'MAL'
    | 'MAT'
    | 'MRK'
    | 'LUK'
    | 'JHN'
    | 'ACT'
    | 'ROM'
    | '1CO'
    | '2CO'
    | 'GAL'
    | 'EPH'
    | 'PHP'
    | 'COL'
    | '1TH'
    | '2TH'
    | '1TI'
    | '2TI'
    | 'TIT'
    | 'PHM'
    | 'HEB'
    | 'JAS'
    | '1PE'
    | '2PE'
    | '1JN'
    | '2JN'
    | '3JN'
    | 'JUD'
    | 'REV'
    | 'TOB'
    | 'JDT'
    | 'ESG'
    | 'WIS'
    | 'SIR'
    | 'BAR'
    | 'LJE'
    | 'S3Y'
    | 'SUS'
    | 'BEL'
    | '1MA'
    | '2MA'
    | '3MA'
    | '4MA'
    | '1ES'
    | '2ES'
    | 'MAN'
    | 'PS2'
    | 'ODA'
    | 'PSS'
    | 'EZA'
    | '5EZ'
    | '6EZ'
    | 'DAG'
    | 'PS3'
    | '2BA'
    | 'LBA'
    | 'JUB'
    | 'ENO'
    | '1MQ'
    | '2MQ'
    | '3MQ'
    | 'REP'
    | '4BA'
    | 'LAO';

/**
 * The list of available translations. Maps to the /api/available-translations.json endpoint.
 */
export type ApiAvailableTranslations = {
    /**
     * The list of translations that are available in the API.
     */
    translations: Array<ApiTranslation>;
};

/**
 * Defines a translation that is used in the API.
 */
export type ApiTranslation = {
    /**
     * The ID of the translation.
     */
    id: string;
    /**
     * The name of the translation.
     */
    name: string;
    /**
     * The website for the translation.
     */
    website: string;
    /**
     * The URL that the license for the translation can be found.
     */
    licenseUrl: string;
    /**
     * The API-added notes for the license.
     */
    licenseNotes?: string | null;
    /**
     * The notice that should be displayed when displaying content from the translation.
     */
    licenseNotice?: string | null;
    /**
     * The short name for the translation.
     */
    shortName?: string;
    /**
     * The English name for the translation.
     */
    englishName: string;
    /**
     * The ISO 639 3-letter language tag that the translation is primarily in.
     */
    language: string;
    /**
     * The direction that the language is written in. `ltr` indicates that the text is written from the left side of the page to the right. `rtl` indicates that the text is written from the right side of the page to the left.
     */
    textDirection: 'ltr' | 'rtl';
    /**
     * The API link for the list of books for this translation. Relative to the API origin.
     */
    listOfBooksApiLink: string;
    availableFormats: Array<'json' | 'usfm'>;
    /**
     * The number of books that are contained in this translation. Complete translations should have the same number of books as the Bible (66).
     */
    numberOfBooks: number;
    /**
     * The total number of chapters that are contained in this translation. Complete translations should have the same number of chapters as the Bible (1,189).
     */
    totalNumberOfChapters: number;
    /**
     * The total number of verses that are contained in this translation. Complete translations should have the same number of verses as the Bible (around 31,102 - some translations exclude verses based on the aparent likelyhood of existing in the original source texts).
     */
    totalNumberOfVerses: number;
    /**
     * The total number of apocryphal books that are contained in this translation.
     */
    numberOfApocryphalBooks?: number;
    /**
     * The total number of apocryphal chapters that are contained in this translation.
     */
    totalNumberOfApocryphalChapters?: number;
    /**
     * The total number of apocryphal verses that are contained in this translation.
     */
    totalNumberOfApocryphalVerses?: number;
    /**
     * Gets the name of the language that the translation is in. Null or undefined if the name of the language is not known.
     */
    languageName?: string;
    /**
     * Gets the name of the language in English. Null or undefined if the language doesn't have an english name.
     */
    languageEnglishName?: string;
    /**
     * The API link for downloading the complete translation as a single JSON file. Relative to the API origin. Undefined if complete translation files are not available.
     */
    completeTranslationApiLink?: string;
};

/**
 * Defines an interface that contains information about the books that are available for a translation.
 */
export type ApiTranslationBooks = {
    /**
     * The translation information for the books.
     */
    translation: ApiTranslation;
    /**
     * The list of books that are available for the translation.
     */
    books: Array<ApiTranslationBook>;
};

/**
 * Defines a schema that contains information about a translation book.
 */
export type ApiTranslationBook = {
    id: BookId;
    /**
     * The name that the translation provided for the book.
     */
    name: string;
    /**
     * The common name for the book.
     */
    commonName: string;
    /**
     * The title of the book. This is usually a more descriptive version of the book name. If not available, then one was not provided by the translation.
     */
    title: string | null;
    /**
     * The numerical order of the book in the translation.
     */
    order: number;
    /**
     * Whether the book is an apocryphal book.
     */
    isApocryphal?: boolean;
    /**
     * The number of the first chapter in the book.
     */
    firstChapterNumber: number;
    /**
     * The link to the first chapter of the book.
     */
    firstChapterApiLink: string;
    firstChapterReference: TranslationChapterReference;
    /**
     * The number of the last chapter in the book.
     */
    lastChapterNumber: number;
    /**
     * The link to the last chapter of the book.
     */
    lastChapterApiLink: string;
    lastChapterReference: TranslationChapterReference;
    /**
     * The number of chapters that the book contains.
     */
    numberOfChapters: number;
    /**
     * The number of verses that the book contains.
     */
    totalNumberOfVerses: number;
};

/**
 * Defines a reference to a chapter in a translation.
 */
export type TranslationChapterReference = {
    /**
     * The ID of the translation that the chapter reference is for.
     */
    translationId: string;
    book: BookId;
    /**
     * The chapter number of the chapter reference.
     */
    chapter: number;
};

/**
 * Defines an interface that contains information about a book chapter in a translation.
 */
export type ApiTranslationBookChapter = {
    /**
     * The information for the chapter.
     */
    chapter: {
        /**
         * The number of the chapter.
         */
        number: number;
        /**
         * The content of the chapter.
         */
        content: Array<ChapterContent>;
        /**
         * The list of footnotes for the chapter.
         */
        footnotes: Array<ChapterFootnote>;
    };
    /**
     * The links to different audio versions for the chapter.
     */
    thisChapterAudioLinks: TranslationBookChapterAudioLinks;
    /**
     * The links to the audio timings for different audio versions for the chapter. Relative to the API origin.
     */
    thisChapterAudioTimings: {
        [key: string]: string;
    };
    /**
     * The translation information for the book chapter.
     */
    translation: ApiTranslation;
    /**
     * The book information for the book chapter.
     */
    book: ApiTranslationBook;
    /**
     * The API link for this chapter. Relative to the API origin.
     */
    thisChapterLink: string;
    thisChapterReference: TranslationChapterReference;
    /**
     * The API link to the next chapter. Relative to the API origin. Null if this is the last chapter in the translation.
     */
    nextChapterApiLink: string | null;
    /**
     * The reference for the next chapter. Null if this is the last chapter in the translation.
     */
    nextChapterReference: TranslationChapterReference | null;
    /**
     * The links to the audio versions for the next chapter. Relative to the API origin. Null if this is the last chapter in the translation.
     */
    nextChapterAudioLinks: {
        [key: string]: string;
    } | null;
    /**
     * The links to the audio timings for different audio versions for the next chapter. Relative to the API origin. Null if this is the last chapter in the translation.
     */
    nextChapterAudioTimings: {
        [key: string]: string;
    } | null;
    /**
     * The links to the audio timings for different audio versions for the previous chapter. Relative to the API origin. Null if this is the first chapter in the translation.
     */
    previousChapterAudioTimings: {
        [key: string]: string;
    } | null;
    /**
     * The API link to the previous chapter. Relative to the API origin. Null if this is the first chapter in the translation.
     */
    previousChapterApiLink: string | null;
    /**
     * The reference for the previous chapter. Null if this is the first chapter in the translation.
     */
    previousChapterReference: TranslationChapterReference | null;
    /**
     * The links to the audio versions for the previous chapter. Relative to the API origin. Null if this is the first chapter in the translation.
     */
    previousChapterAudioLinks: {
        [key: string]: string;
    } | null;
    /**
     * The link to the word-level annotations for this chapter. Relative to the API origin. Omitted if the chapter doesn't have any word-level annotations.
     */
    thisChapterWordsLink?: string;
    /**
     * The link to the word-level annotations for the next chapter. Relative to the API origin. Omitted if this is the last chapter in the translation, or if the next chapter doesn't have any word-level annotations.
     */
    nextChapterWordsLink?: string;
    /**
     * The link to the word-level annotations for the previous chapter. Relative to the API origin. Omitted if this is the first chapter in the translation, or if the previous chapter doesn't have any word-level annotations.
     */
    previousChapterWordsLink?: string;
    /**
     * The number of verses that the chapter contains.
     */
    numberOfVerses: number;
};

/**
 * Defines a union type that represents a single piece of chapter content. A piece of chapter content can be one of the following things: A heading, a line break, a verse, or a Hebrew Subtitle.
 */
export type ChapterContent =
    | ({
          type: 'heading';
      } & ChapterHeading)
    | ({
          type: 'line_break';
      } & ChapterLineBreak)
    | ({
          type: 'verse';
      } & ChapterVerse)
    | ({
          type: 'hebrew_subtitle';
      } & ChapterHebrewSubtitle);

/**
 * Defines the schema for a heading in a chapter.
 */
export type ChapterHeading = {
    type: 'heading';
    /**
     * The content for the heading. If multiple strings are included in the array, they should be concatenated with a space.
     */
    content: Array<string>;
};

/**
 * Defines the schema for a line break in a chapter.
 */
export type ChapterLineBreak = {
    type: 'line_break';
};

/**
 * Defines the schema for a verse in a chapter.
 */
export type ChapterVerse = {
    type: 'verse';
    /**
     * The number of the verse.
     */
    number: number;
    /**
     * The list of content for the verse. Each element in the list could be a string, formatted text, or a footnote reference.
     */
    content: Array<
        | string
        | FormattedText
        | InlineHeading
        | InlineLineBreak
        | VerseFootnoteReference
    >;
};

/**
 * Defines the schema for formatted text. That is, text that is formatted in a particular manner.
 */
export type FormattedText = {
    /**
     * The text that is formatted.
     */
    text: string;
    /**
     * Whether the text represents a poem. The number indicates the level of indent. Common in Psalms.
     */
    poem?: number;
    /**
     * Whether the text represents the Words of Jesus.
     */
    wordsOfJesus?: boolean;
};

/**
 * Defines the schema for a heading that is embedded in a verse.
 */
export type InlineHeading = {
    /**
     * The text of the heading.
     */
    heading: string;
};

/**
 * Defines the schema for a line break that is embedded in a verse.
 */
export type InlineLineBreak = {
    lineBreak: true;
};

/**
 * Defines the schema for a footnote reference in a verse or a Hebrew Subtitle.
 */
export type VerseFootnoteReference = {
    /**
     * The ID of the note.
     */
    noteId: number;
};

/**
 * Defines the schema for a Hebrew Subtitle in a chapter.
 */
export type ChapterHebrewSubtitle = {
    type: 'hebrew_subtitle';
    /**
     * The content that is contained in the subtitle. Each element in the list could be a string, formatted text, or a footnote reference.
     */
    content: Array<string | FormattedText | VerseFootnoteReference>;
};

/**
 * Defines the schema for information about a footnote.
 */
export type ChapterFootnote = {
    /**
     * The ID of the note that is referenced.
     */
    noteId: number;
    /**
     * The text of the footnote.
     */
    text: string;
    /**
     * The verse reference for the footnote. Undefined if the footnote isn't associated with a specific verse.
     */
    reference?: {
        chapter: number;
        verse: number;
    };
    /**
     * The caller that should be used for the footnote. For footnotes, a "caller" is the character that is used in the text to reference to footnote. For example, in the text: Hello (a) World ---- (a) This is a footnote. The "(a)" is the caller. If "+", then the caller should be autogenerated. If null, then the caller should be empty. If a string, then the caller should be that string.
     */
    caller: '+' | string | null;
};

/**
 * Defines the schema for the audio links for a book chapter.
 */
export type TranslationBookChapterAudioLinks = {
    [key: string]: string;
};

/**
 * Defines an interface that contains the audio timings for a book chapter, for a specific reader.
 */
export type ApiTranslationBookChapterAudioTimings = {
    /**
     * The ID of the translation.
     */
    translationId: string;
    /**
     * The ID of the book.
     */
    bookId: string;
    /**
     * The number of the chapter.
     */
    chapterNumber: number;
    /**
     * The reader for the chapter.
     */
    reader: string;
    /**
     * The link to the audio for these timings.
     */
    audioLink: string;
    /**
     * The link to the information for this chapter.
     */
    thisChapterLink: string;
    /**
     * The link to the information for the next chapter. Null if this is the last chapter in the translation.
     */
    nextChapterLink: string | null;
    /**
     * The link to the information for the previous chapter. Null if this is the first chapter in the translation.
     */
    previousChapterLink: string | null;
    /**
     * The link to this audio timings file.
     */
    thisChapterAudioTimingsLink: string;
    /**
     * The link to the timings for the next chapter. Null if this is the last chapter in the translation.
     */
    nextChapterAudioTimingsLink: string | null;
    /**
     * The link to the timings for the previous chapter. Null if this is the first chapter in the translation.
     */
    previousChapterAudioTimingsLink: string | null;
    /**
     * The times in seconds at which each verse starts, in order. The first number (index 0) is the time in the recording at which the first verse starts.
     */
    verses: Array<number>;
};

/**
 * Defines an interface that contains the word-level annotations for a book chapter.
 */
export type ApiTranslationBookChapterWords = {
    /**
     * The ID of the translation.
     */
    translationId: string;
    /**
     * The ID of the book.
     */
    bookId: string;
    /**
     * The number of the chapter.
     */
    chapterNumber: number;
    /**
     * The link to the information for this chapter.
     */
    thisChapterLink: string;
    /**
     * The link to the information for the next chapter. Null if this is the last chapter in the translation.
     */
    nextChapterLink: string | null;
    /**
     * The link to the information for the previous chapter. Null if this is the first chapter in the translation.
     */
    previousChapterLink: string | null;
    /**
     * The link to this words file.
     */
    thisChapterWordsLink: string;
    /**
     * The link to the words for the next chapter. Null if this is the last chapter in the translation, or if the next chapter doesn't have any word-level annotations.
     */
    nextChapterWordsLink: string | null;
    /**
     * The link to the words for the previous chapter. Null if this is the first chapter in the translation, or if the previous chapter doesn't have any word-level annotations.
     */
    previousChapterWordsLink: string | null;
    /**
     * The annotated words for each verse in the chapter, keyed by verse number. Each list is in the order that the words occur in the verse.
     */
    verses: {
        [key: string]: Array<ChapterWord>;
    };
};

/**
 * Defines the schema for a word-level annotation in a chapter. The annotation is anchored to a range of characters in a single item of a verse's content.
 */
export type ChapterWord = {
    /**
     * The index of the item in the verse's content array that the annotation applies to.
     */
    contentIndex: number;
    /**
     * The index of the first character of the annotated word in the content item's text.
     */
    start: number;
    /**
     * The index after the last character of the annotated word in the content item's text. That is, text.slice(start, end) is the annotated word.
     */
    end: number;
    /**
     * The Strong's number(s) for the word. Omitted if the translation only provided other annotations for the word.
     */
    strongs?: Array<string>;
    /**
     * The dictionary (citation) form of the word. Omitted if the translation did not provide one.
     */
    lemma?: string;
    /**
     * The morphology parse code for the word. Omitted if the translation did not provide one.
     */
    morph?: string;
    /**
     * The pointer to the word in the source text, in the <sourceName>:<location> format. Omitted if the translation did not provide one.
     */
    srcloc?: string;
    /**
     * Which occurrence of the source word this word is. 1-based. Omitted if the translation did not provide one.
     */
    occurrence?: number;
    /**
     * The total number of times that the source word occurs. Omitted if the translation did not provide one.
     */
    occurrences?: number;
};

/**
 * Defines the complete translation download data. Maps to the /api/:translationId/complete.json endpoint.
 */
export type ApiTranslationComplete = {
    /**
     * The translation metadata.
     */
    translation: ApiTranslation;
    /**
     * The complete list of books with all their chapters.
     */
    books: Array<ApiTranslationCompleteBook>;
};

/**
 * A book in the complete translation download.
 */
export type ApiTranslationCompleteBook = {
    id: BookId;
    /**
     * The name that the translation provided for the book.
     */
    name: string;
    /**
     * The common name for the book.
     */
    commonName: string;
    /**
     * The title of the book. This is usually a more descriptive version of the book name. If not available, then one was not provided by the translation.
     */
    title: string | null;
    /**
     * The numerical order of the book in the translation.
     */
    order: number;
    /**
     * Whether the book is an apocryphal book.
     */
    isApocryphal?: boolean;
    /**
     * The number of chapters in the book.
     */
    numberOfChapters: number;
    /**
     * The total number of verses in the book.
     */
    totalNumberOfVerses: number;
    /**
     * The complete list of chapters with all content.
     */
    chapters: Array<TranslationBookChapter>;
};

/**
 * Defines the schema for information about a book chapter.
 */
export type TranslationBookChapter = {
    /**
     * The information for the chapter.
     */
    chapter: {
        /**
         * The number of the chapter.
         */
        number: number;
        /**
         * The content of the chapter.
         */
        content: Array<ChapterContent>;
        /**
         * The list of footnotes for the chapter.
         */
        footnotes: Array<ChapterFootnote>;
    };
    /**
     * The links to different audio versions for the chapter.
     */
    thisChapterAudioLinks: TranslationBookChapterAudioLinks;
    /**
     * The audio timings (per-verse start times, in seconds) for different audio versions for the chapter.
     */
    thisChapterAudioTimings: TranslationBookChapterAudioTimings;
    /**
     * The word-level annotations (Strong's numbers and related source data) for the chapter's verses. Omitted if the translation doesn't have any word-level annotations for the chapter.
     */
    thisChapterWords?: TranslationBookChapterWords;
};

/**
 * Defines the schema for the audio timings for a book chapter. Maps a reader ID to the list of times (in seconds) that each verse starts, in verse order.
 */
export type TranslationBookChapterAudioTimings = {
    [key: string]: Array<number>;
};

/**
 * Defines the schema for the word-level annotations for a book chapter. Maps a verse number to the list of annotated words in the verse, in order.
 */
export type TranslationBookChapterWords = {
    [key: string]: Array<ChapterWord>;
};

/**
 * The list of available commentaries. Maps to the /api/available-commentaries.json endpoint.
 */
export type ApiAvailableCommentaries = {
    /**
     * The list of commentaries that are available in the API.
     */
    commentaries: Array<ApiCommentary>;
};

/**
 * Defines a commentary that is used in the API.
 */
export type ApiCommentary = {
    /**
     * The ID of the commentary.
     */
    id: string;
    /**
     * The name of the commentary.
     */
    name: string;
    /**
     * The website for the commentary.
     */
    website: string;
    /**
     * The URL that the license for the commentary can be found.
     */
    licenseUrl: string;
    /**
     * The API-added notes for the license.
     */
    licenseNotes?: string | null;
    /**
     * The English name for the commentary.
     */
    englishName: string;
    /**
     * The ISO 639 3-letter language tag that the translation is primarily in.
     */
    language: string;
    /**
     * The direction that the language is written in. `ltr` indicates that the text is written from the left side of the page to the right. `rtl` indicates that the text is written from the right side of the page to the left.
     */
    textDirection: 'ltr' | 'rtl';
    /**
     * The API link for the list of books for this commentary. Relative to the API origin.
     */
    listOfBooksApiLink: string;
    /**
     * The API link for the list of profiles for this commentary. Relative to the API origin.
     */
    listOfProfilesApiLink: string;
    availableFormats: Array<'json' | 'usfm'>;
    /**
     * The number of books that are contained in this commentary. Complete commentaries should have the same number of books as the Bible (66).
     */
    numberOfBooks: number;
    /**
     * The total number of chapters that are contained in this commentary. Complete commentaries should have the same number of chapters as the Bible (1,189).
     */
    totalNumberOfChapters: number;
    /**
     * The total number of verses that are contained in this commentary. Complete commentaries should have the same number of verses as the Bible (around 31,102 - some commentaries exclude verses based on the aparent likelyhood of existing in the original source texts).
     */
    totalNumberOfVerses: number;
    /**
     * The total number of profiles that are contained in this commentary. Profiles are used to provide additional information about people and people groups that are mentioned in the Bible.
     */
    totalNumberOfProfiles: number;
    /**
     * Gets the name of the language that the commentary is in. Null or undefined if the name of the language is not known.
     */
    languageName?: string;
    /**
     * Gets the name of the language in English. Null or undefined if the language doesn't have an english name.
     */
    languageEnglishName?: string;
};

/**
 * Defines an interface that contains information about the books that are available for a commentary.
 */
export type ApiCommentaryBooks = {
    /**
     * The commentary information for the books.
     */
    commentary: ApiCommentary;
    /**
     * The list of books that are available for the commentary.
     */
    books: Array<ApiCommentaryBook>;
};

/**
 * Defines a schema that contains information about a commentary book.
 */
export type ApiCommentaryBook = {
    id: BookId;
    /**
     * The name that the commentary provided for the book.
     */
    name: string;
    /**
     * The common name for the book.
     */
    commonName: string;
    /**
     * The commentary's introduction for the book. Undefined if the commentary didn't provide an introduction for the book.
     */
    introduction?: string;
    /**
     * The summary of the commentary's introduction for the book. Undefined if the commentary didn't provide a summary for the book.
     */
    introductionSummary?: string;
    /**
     * The order of the book in the Bible.
     */
    order: number;
    /**
     * The number of the first chapter in the book. Null if the comentary book has no chapters.
     */
    firstChapterNumber: number | null;
    /**
     * The link to the first chapter of the book. Null if the comentary book has no chapters.
     */
    firstChapterApiLink: string | null;
    /**
     * The reference for the first chapter in the book. Null if the comentary book has no chapters.
     */
    firstChapterReference: CommentaryChapterReference | null;
    /**
     * The number of the last chapter in the book. Null if the comentary book has no chapters.
     */
    lastChapterNumber: number | null;
    /**
     * The link to the last chapter of the book. Null if the comentary book has no chapters.
     */
    lastChapterApiLink: string | null;
    /**
     * The reference for the last chapter in the book. Null if the comentary book has no chapters.
     */
    lastChapterReference: CommentaryChapterReference | null;
    /**
     * The number of chapters that the book contains.
     */
    numberOfChapters: number;
    /**
     * The number of verses that the book contains.
     */
    totalNumberOfVerses: number;
};

/**
 * Defines a reference to a chapter in a commentary.
 */
export type CommentaryChapterReference = {
    /**
     * The ID of the commentary that the chapter reference is for.
     */
    commentaryId: string;
    book: BookId;
    /**
     * The chapter number of the chapter reference.
     */
    chapter: number;
};

/**
 * Defines a schema that contains information about a book chapter in a commentary.
 */
export type ApiCommentaryBookChapter = {
    /**
     * The information for the chapter.
     */
    chapter: {
        /**
         * The number of the chapter.
         */
        number: number;
        /**
         * The introduction that the commentary provided to the chapter. Not all commentaries provide an introduction to a chapter.
         */
        introduction?: string;
        /**
         * The content of the chapter.
         */
        content: Array<ChapterVerse>;
    };
    /**
     * The commentary information for the book chapter.
     */
    commentary: ApiCommentary;
    /**
     * The book information for the book chapter.
     */
    book: ApiCommentaryBook;
    /**
     * The API link for this chapter. Relative to the API origin.
     */
    thisChapterLink: string;
    thisChapterReference: CommentaryChapterReference;
    /**
     * The API link to the next chapter. Relative to the API origin. Null if this is the last chapter in the commentary.
     */
    nextChapterApiLink: string | null;
    /**
     * The reference for the next chapter. Null if this is the last chapter in the commentary.
     */
    nextChapterReference: CommentaryChapterReference | null;
    /**
     * The API link to the previous chapter. Relative to the API origin. Null if this is the first chapter in the commentary.
     */
    previousChapterApiLink: string | null;
    /**
     * The reference for the previous chapter. Null if this is the first chapter in the commentary.
     */
    previousChapterReference: CommentaryChapterReference | null;
    /**
     * The number of verses that the chapter contains.
     */
    numberOfVerses: number;
};

/**
 * The list of available datasets. Maps to the /api/available-datasets.json endpoint.
 */
export type ApiAvailableDatasets = {
    /**
     * The list of datasets that are available in the API.
     */
    datasets: Array<ApiDataset>;
};

/**
 * Defines a dataset that is used in the API.
 */
export type ApiDataset = {
    /**
     * The ID of the dataset.
     */
    id: string;
    /**
     * The name of the dataset.
     */
    name: string;
    /**
     * The website for the dataset.
     */
    website: string;
    /**
     * The URL that the license for the dataset can be found.
     */
    licenseUrl: string;
    /**
     * The API-added notes for the license.
     */
    licenseNotes?: string | null;
    /**
     * The English name for the dataset.
     */
    englishName: string;
    /**
     * The ISO 639 3-letter language tag that the dataset is primarily in.
     */
    language: string;
    /**
     * The direction that the language is written in.
     */
    textDirection: 'ltr' | 'rtl';
    /**
     * The API link for the list of books for this dataset. Relative to the API origin.
     */
    listOfBooksApiLink: string;
    availableFormats: Array<'json'>;
    /**
     * The number of books that are contained in this dataset.
     */
    numberOfBooks: number;
    /**
     * The total number of chapters that are contained in this dataset.
     */
    totalNumberOfChapters: number;
    /**
     * The total number of verses that are contained in this dataset.
     */
    totalNumberOfVerses: number;
    /**
     * The total number of references that are contained in this dataset.
     */
    totalNumberOfReferences: number;
    /**
     * Gets the name of the language that the dataset is in. Null or undefined if the name of the language is not known.
     */
    languageName?: string;
    /**
     * Gets the name of the language in English. Null or undefined if the language doesn't have an english name.
     */
    languageEnglishName?: string;
};

/**
 * Defines an interface that contains information about the books that are available for a dataset.
 */
export type ApiDatasetBooks = {
    /**
     * The dataset information for the books.
     */
    dataset: ApiDataset;
    /**
     * The list of books that are available for the dataset.
     */
    books: Array<ApiDatasetBook>;
};

/**
 * Defines a schema that contains information about a book in a dataset.
 */
export type ApiDatasetBook = {
    id: BookId;
    /**
     * The order of the book in the Bible.
     */
    order: number;
    /**
     * The number of the first chapter in the book.
     */
    firstChapterNumber: number;
    /**
     * The link to the first chapter of the book.
     */
    firstChapterApiLink: string;
    firstChapterReference: DatasetChapterReference;
    /**
     * The number of the last chapter in the book.
     */
    lastChapterNumber: number;
    /**
     * The link to the last chapter of the book.
     */
    lastChapterApiLink: string;
    lastChapterReference: DatasetChapterReference;
    /**
     * The number of chapters that the book contains.
     */
    numberOfChapters: number;
    /**
     * The number of verses that the book contains.
     */
    totalNumberOfVerses: number;
    /**
     * The number of references that the book contains.
     */
    totalNumberOfReferences: number;
};

/**
 * Defines a reference to a chapter in a dataset.
 */
export type DatasetChapterReference = {
    /**
     * The ID of the dataset that the chapter reference is for.
     */
    datasetId: string;
    book: BookId;
    /**
     * The chapter number of the chapter reference.
     */
    chapter: number;
};

/**
 * Defines a schema that contains information about a book chapter in a dataset.
 */
export type ApiDatasetBookChapter = {
    /**
     * The data for the chapter.
     */
    chapter: DatasetChapterData;
    /**
     * The dataset information for the book chapter.
     */
    dataset: ApiDataset;
    /**
     * The book information for the book chapter.
     */
    book: ApiDatasetBook;
    /**
     * The API link for this chapter. Relative to the API origin.
     */
    thisChapterLink: string;
    thisChapterReference: DatasetChapterReference;
    /**
     * The API link to the next chapter. Relative to the API origin. Null if this is the last chapter in the dataset.
     */
    nextChapterApiLink: string | null;
    /**
     * The reference for the next chapter. Null if this is the last chapter in the dataset.
     */
    nextChapterReference: DatasetChapterReference | null;
    /**
     * The API link to the previous chapter. Relative to the API origin. Null if this is the first chapter in the dataset.
     */
    previousChapterApiLink: string | null;
    /**
     * The reference for the previous chapter. Null if this is the first chapter in the dataset.
     */
    previousChapterReference: DatasetChapterReference | null;
    /**
     * The number of verses that the chapter contains.
     */
    numberOfVerses: number;
    /**
     * The number of references that the chapter contains.
     */
    numberOfReferences: number;
};

/**
 * Defines the schema for information about a chapter in a dataset.
 */
export type DatasetChapterData = {
    /**
     * The number of the chapter.
     */
    number: number;
    /**
     * The content of the chapter.
     */
    content: Array<DatasetChapterVerseContent>;
};

/**
 * Defines the schema for information about a verse in a dataset chapter.
 */
export type DatasetChapterVerseContent = {
    /**
     * The number of the verse.
     */
    verse: number;
    /**
     * The list of references for the verse.
     */
    references: Array<ScoredVerseRef>;
};

/**
 * Defines the schema for information about a verse reference that has an arbitrary score attached to it.
 */
export type ScoredVerseRef = {
    book: BookId;
    /**
     * The chapter number that the reference starts at.
     */
    chapter: number;
    /**
     * The verse number that the reference starts at.
     */
    verse: number;
    /**
     * The rest of the content of the verse reference. This is the part of the string that comes after the verse reference. For example, in "GEN 1:1 In the beginning, God created the Heavens and the Earth.", the content would be "In the beginning, God created the Heavens and the Earth."
     */
    content?: string;
    /**
     * The chapter that the verse reference ends at. This is used for references that span multiple chapters, such as "GEN 1:1-2:3". In this case, the endChapter would be 2.
     */
    endChapter?: number;
    /**
     * The verse that the verse reference ends at. This is used for references that span multiple verses, such as "GEN 1:1-1:3". In this case, the endVerse would be 3.
     */
    endVerse?: number;
    /**
     * The score for the verse reference. The meaning of the score is arbitrary and is determined by the dataset.
     */
    score: number;
};

export type GetAvailableTranslationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/available_translations.json';
};

export type GetAvailableTranslationsResponses = {
    /**
     * 200 OK
     */
    200: ApiAvailableTranslations;
};

export type GetAvailableTranslationsResponse =
    GetAvailableTranslationsResponses[keyof GetAvailableTranslationsResponses];

export type GetTranslationBooksData = {
    body?: never;
    path: {
        /**
         * The translation ID of the Bible translation to get the books for. For example, "eng_kjv" for the King James Version.
         */
        translation: string;
    };
    query?: never;
    url: '/api/{translation}/books.json';
};

export type GetTranslationBooksErrors = {
    /**
     * 404 Not Found - The specified translation was not found.
     */
    404: unknown;
};

export type GetTranslationBooksResponses = {
    /**
     * 200 OK
     */
    200: ApiTranslationBooks;
};

export type GetTranslationBooksResponse =
    GetTranslationBooksResponses[keyof GetTranslationBooksResponses];

export type GetTranslationBookChapterData = {
    body?: never;
    path: {
        /**
         * The translation ID of the Bible translation to get the books for. For example, "eng_kjv" for the King James Version.
         */
        translation: string;
        /**
         * IDs for books. Follows the USFM standard (https://ubsicap.github.io/usfm/identification/books.html)
         */
        book: BookId;
        /**
         * The chapter number to get the content for. This should be a positive integer.
         */
        chapter: number;
    };
    query?: never;
    url: '/api/{translation}/{book}/{chapter}.json';
};

export type GetTranslationBookChapterErrors = {
    /**
     * 404 Not Found - The specified translation, book, or chapter was not found.
     */
    404: unknown;
};

export type GetTranslationBookChapterResponses = {
    /**
     * 200 OK
     */
    200: ApiTranslationBookChapter;
};

export type GetTranslationBookChapterResponse =
    GetTranslationBookChapterResponses[keyof GetTranslationBookChapterResponses];

export type GetTranslationBookChapterAudioTimingsData = {
    body?: never;
    path: {
        /**
         * The translation ID of the Bible translation to get the books for. For example, "eng_kjv" for the King James Version.
         */
        translation: string;
        /**
         * IDs for books. Follows the USFM standard (https://ubsicap.github.io/usfm/identification/books.html)
         */
        book: BookId;
        /**
         * The chapter number to get the content for. This should be a positive integer.
         */
        chapter: number;
        /**
         * The ID of the reader to get the audio timings for. For example, "hays" for the Hays reading of the Berean Standard Bible.
         */
        reader: string;
    };
    query?: never;
    url: '/api/{translation}/{book}/{chapter}.{reader}.audioTimings.json';
};

export type GetTranslationBookChapterAudioTimingsErrors = {
    /**
     * 404 Not Found - The specified translation, book, chapter, or reader was not found.
     */
    404: unknown;
};

export type GetTranslationBookChapterAudioTimingsResponses = {
    /**
     * 200 OK
     */
    200: ApiTranslationBookChapterAudioTimings;
};

export type GetTranslationBookChapterAudioTimingsResponse =
    GetTranslationBookChapterAudioTimingsResponses[keyof GetTranslationBookChapterAudioTimingsResponses];

export type GetTranslationBookChapterWordsData = {
    body?: never;
    path: {
        /**
         * The translation ID of the Bible translation to get the books for. For example, "eng_kjv" for the King James Version.
         */
        translation: string;
        /**
         * IDs for books. Follows the USFM standard (https://ubsicap.github.io/usfm/identification/books.html)
         */
        book: BookId;
        /**
         * The chapter number to get the content for. This should be a positive integer.
         */
        chapter: number;
    };
    query?: never;
    url: '/api/{translation}/{book}/{chapter}.words.json';
};

export type GetTranslationBookChapterWordsErrors = {
    /**
     * 404 Not Found - The specified translation, book, or chapter was not found, or the chapter does not have any word-level annotations.
     */
    404: unknown;
};

export type GetTranslationBookChapterWordsResponses = {
    /**
     * 200 OK
     */
    200: ApiTranslationBookChapterWords;
};

export type GetTranslationBookChapterWordsResponse =
    GetTranslationBookChapterWordsResponses[keyof GetTranslationBookChapterWordsResponses];

export type GetTranslationCompleteData = {
    body?: never;
    path: {
        /**
         * The translation ID of the Bible translation to get the books for. For example, "eng_kjv" for the King James Version.
         */
        translation: string;
    };
    query?: never;
    url: '/api/{translation}/complete.json';
};

export type GetTranslationCompleteErrors = {
    /**
     * 404 Not Found - The specified translation was not found, or complete translations are not available.
     */
    404: unknown;
};

export type GetTranslationCompleteResponses = {
    /**
     * 200 OK
     */
    200: ApiTranslationComplete;
};

export type GetTranslationCompleteResponse =
    GetTranslationCompleteResponses[keyof GetTranslationCompleteResponses];

export type GetAvailableCommentariesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/available_commentaries.json';
};

export type GetAvailableCommentariesResponses = {
    /**
     * 200 OK
     */
    200: ApiAvailableCommentaries;
};

export type GetAvailableCommentariesResponse =
    GetAvailableCommentariesResponses[keyof GetAvailableCommentariesResponses];

export type GetCommentaryBooksData = {
    body?: never;
    path: {
        /**
         * The commentary ID of the commentary to get the books or chapter content for.
         */
        commentary: string;
    };
    query?: never;
    url: '/api/c/{commentary}/books.json';
};

export type GetCommentaryBooksErrors = {
    /**
     * 404 Not Found - The specified commentary was not found.
     */
    404: unknown;
};

export type GetCommentaryBooksResponses = {
    /**
     * 200 OK
     */
    200: ApiCommentaryBooks;
};

export type GetCommentaryBooksResponse =
    GetCommentaryBooksResponses[keyof GetCommentaryBooksResponses];

export type GetCommentaryBookChapterData = {
    body?: never;
    path: {
        /**
         * The commentary ID of the commentary to get the books or chapter content for.
         */
        commentary: string;
        /**
         * IDs for books. Follows the USFM standard (https://ubsicap.github.io/usfm/identification/books.html)
         */
        book: BookId;
        /**
         * The chapter number to get the content for. This should be a positive integer.
         */
        chapter: number;
    };
    query?: never;
    url: '/api/c/{commentary}/{book}/{chapter}.json';
};

export type GetCommentaryBookChapterErrors = {
    /**
     * 404 Not Found - The specified commentary, book, or chapter was not found.
     */
    404: unknown;
};

export type GetCommentaryBookChapterResponses = {
    /**
     * 200 OK
     */
    200: ApiCommentaryBookChapter;
};

export type GetCommentaryBookChapterResponse =
    GetCommentaryBookChapterResponses[keyof GetCommentaryBookChapterResponses];

export type GetAvailableDatasetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/available_datasets.json';
};

export type GetAvailableDatasetsResponses = {
    /**
     * 200 OK
     */
    200: ApiAvailableDatasets;
};

export type GetAvailableDatasetsResponse =
    GetAvailableDatasetsResponses[keyof GetAvailableDatasetsResponses];

export type GetDatasetBooksData = {
    body?: never;
    path: {
        /**
         * The dataset ID of the dataset to get the books or chapter content for.
         */
        dataset: string;
    };
    query?: never;
    url: '/api/d/{dataset}/books.json';
};

export type GetDatasetBooksErrors = {
    /**
     * 404 Not Found - The specified dataset was not found.
     */
    404: unknown;
};

export type GetDatasetBooksResponses = {
    /**
     * 200 OK
     */
    200: ApiDatasetBooks;
};

export type GetDatasetBooksResponse =
    GetDatasetBooksResponses[keyof GetDatasetBooksResponses];

export type GetDatasetBookChapterData = {
    body?: never;
    path: {
        /**
         * The dataset ID of the dataset to get the books or chapter content for.
         */
        dataset: string;
        /**
         * IDs for books. Follows the USFM standard (https://ubsicap.github.io/usfm/identification/books.html)
         */
        book: BookId;
        /**
         * The chapter number to get the content for. This should be a positive integer.
         */
        chapter: number;
    };
    query?: never;
    url: '/api/d/{dataset}/{book}/{chapter}.json';
};

export type GetDatasetBookChapterErrors = {
    /**
     * 404 Not Found - The specified dataset, book, or chapter was not found.
     */
    404: unknown;
};

export type GetDatasetBookChapterResponses = {
    /**
     * 200 OK
     */
    200: ApiDatasetBookChapter;
};

export type GetDatasetBookChapterResponse =
    GetDatasetBookChapterResponses[keyof GetDatasetBookChapterResponses];
