/**
 * Book names in multiple languages.
 * This file contains translations of Bible book names for use with Beblia XML imports.
 *
 * Sources:
 * - Bible SuperSearch (https://www.biblesupersearch.com/bible-downloads/)
 * - Various Bible translation projects
 *
 * Language codes follow ISO 639-3 standard.
 */

export interface BookNameEntry {
    commonName: string;
}

type BookNameMap = Map<string, BookNameEntry>;

/**
 * Romanian book names
 */
export const romanianBookMap: BookNameMap = new Map([
    ['GEN', { commonName: 'Geneza' }],
    ['EXO', { commonName: 'Exodul' }],
    ['LEV', { commonName: 'Leviticul' }],
    ['NUM', { commonName: 'Numeri' }],
    ['DEU', { commonName: 'Deuteronomul' }],
    ['JOS', { commonName: 'Iosua' }],
    ['JDG', { commonName: 'Judecătorii' }],
    ['RUT', { commonName: 'Rut' }],
    ['1SA', { commonName: '1 Samuel' }],
    ['2SA', { commonName: '2 Samuel' }],
    ['1KI', { commonName: '1 Împărați' }],
    ['2KI', { commonName: '2 Împărați' }],
    ['1CH', { commonName: '1 Cronici' }],
    ['2CH', { commonName: '2 Cronici' }],
    ['EZR', { commonName: 'Ezra' }],
    ['NEH', { commonName: 'Neemia' }],
    ['EST', { commonName: 'Estera' }],
    ['JOB', { commonName: 'Iov' }],
    ['PSA', { commonName: 'Psalmii' }],
    ['PRO', { commonName: 'Proverbele' }],
    ['ECC', { commonName: 'Eclesiastul' }],
    ['SNG', { commonName: 'Cântarea Cântărilor' }],
    ['ISA', { commonName: 'Isaia' }],
    ['JER', { commonName: 'Ieremia' }],
    ['LAM', { commonName: 'Plângerile lui Ieremia' }],
    ['EZK', { commonName: 'Ezechiel' }],
    ['DAN', { commonName: 'Daniel' }],
    ['HOS', { commonName: 'Osea' }],
    ['JOL', { commonName: 'Ioel' }],
    ['AMO', { commonName: 'Amos' }],
    ['OBA', { commonName: 'Obadia' }],
    ['JON', { commonName: 'Iona' }],
    ['MIC', { commonName: 'Mica' }],
    ['NAM', { commonName: 'Naum' }],
    ['HAB', { commonName: 'Habacuc' }],
    ['ZEP', { commonName: 'Țefania' }],
    ['HAG', { commonName: 'Hagai' }],
    ['ZEC', { commonName: 'Zaharia' }],
    ['MAL', { commonName: 'Maleahi' }],
    ['MAT', { commonName: 'Matei' }],
    ['MRK', { commonName: 'Marcu' }],
    ['LUK', { commonName: 'Luca' }],
    ['JHN', { commonName: 'Ioan' }],
    ['ACT', { commonName: 'Faptele Apostolilor' }],
    ['ROM', { commonName: 'Romani' }],
    ['1CO', { commonName: '1 Corinteni' }],
    ['2CO', { commonName: '2 Corinteni' }],
    ['GAL', { commonName: 'Galateni' }],
    ['EPH', { commonName: 'Efeseni' }],
    ['PHP', { commonName: 'Filipeni' }],
    ['COL', { commonName: 'Coloseni' }],
    ['1TH', { commonName: '1 Tesaloniceni' }],
    ['2TH', { commonName: '2 Tesaloniceni' }],
    ['1TI', { commonName: '1 Timotei' }],
    ['2TI', { commonName: '2 Timotei' }],
    ['TIT', { commonName: 'Tit' }],
    ['PHM', { commonName: 'Filimon' }],
    ['HEB', { commonName: 'Evrei' }],
    ['JAS', { commonName: 'Iacov' }],
    ['1PE', { commonName: '1 Petru' }],
    ['2PE', { commonName: '2 Petru' }],
    ['1JN', { commonName: '1 Ioan' }],
    ['2JN', { commonName: '2 Ioan' }],
    ['3JN', { commonName: '3 Ioan' }],
    ['JUD', { commonName: 'Iuda' }],
    ['REV', { commonName: 'Apocalipsa' }],
]);

/**
 * Spanish book names
 */
export const spanishBookMap: BookNameMap = new Map([
    ['GEN', { commonName: 'Génesis' }],
    ['EXO', { commonName: 'Éxodo' }],
    ['LEV', { commonName: 'Levítico' }],
    ['NUM', { commonName: 'Números' }],
    ['DEU', { commonName: 'Deuteronomio' }],
    ['JOS', { commonName: 'Josué' }],
    ['JDG', { commonName: 'Jueces' }],
    ['RUT', { commonName: 'Rut' }],
    ['1SA', { commonName: '1 Samuel' }],
    ['2SA', { commonName: '2 Samuel' }],
    ['1KI', { commonName: '1 Reyes' }],
    ['2KI', { commonName: '2 Reyes' }],
    ['1CH', { commonName: '1 Crónicas' }],
    ['2CH', { commonName: '2 Crónicas' }],
    ['EZR', { commonName: 'Esdras' }],
    ['NEH', { commonName: 'Nehemías' }],
    ['EST', { commonName: 'Ester' }],
    ['JOB', { commonName: 'Job' }],
    ['PSA', { commonName: 'Salmos' }],
    ['PRO', { commonName: 'Proverbios' }],
    ['ECC', { commonName: 'Eclesiastés' }],
    ['SNG', { commonName: 'Cantares' }],
    ['ISA', { commonName: 'Isaías' }],
    ['JER', { commonName: 'Jeremías' }],
    ['LAM', { commonName: 'Lamentaciones' }],
    ['EZK', { commonName: 'Ezequiel' }],
    ['DAN', { commonName: 'Daniel' }],
    ['HOS', { commonName: 'Oseas' }],
    ['JOL', { commonName: 'Joel' }],
    ['AMO', { commonName: 'Amós' }],
    ['OBA', { commonName: 'Abdías' }],
    ['JON', { commonName: 'Jonás' }],
    ['MIC', { commonName: 'Miqueas' }],
    ['NAM', { commonName: 'Nahúm' }],
    ['HAB', { commonName: 'Habacuc' }],
    ['ZEP', { commonName: 'Sofonías' }],
    ['HAG', { commonName: 'Hageo' }],
    ['ZEC', { commonName: 'Zacarías' }],
    ['MAL', { commonName: 'Malaquías' }],
    ['MAT', { commonName: 'Mateo' }],
    ['MRK', { commonName: 'Marcos' }],
    ['LUK', { commonName: 'Lucas' }],
    ['JHN', { commonName: 'Juan' }],
    ['ACT', { commonName: 'Hechos' }],
    ['ROM', { commonName: 'Romanos' }],
    ['1CO', { commonName: '1 Corintios' }],
    ['2CO', { commonName: '2 Corintios' }],
    ['GAL', { commonName: 'Gálatas' }],
    ['EPH', { commonName: 'Efesios' }],
    ['PHP', { commonName: 'Filipenses' }],
    ['COL', { commonName: 'Colosenses' }],
    ['1TH', { commonName: '1 Tesalonicenses' }],
    ['2TH', { commonName: '2 Tesalonicenses' }],
    ['1TI', { commonName: '1 Timoteo' }],
    ['2TI', { commonName: '2 Timoteo' }],
    ['TIT', { commonName: 'Tito' }],
    ['PHM', { commonName: 'Filemón' }],
    ['HEB', { commonName: 'Hebreos' }],
    ['JAS', { commonName: 'Santiago' }],
    ['1PE', { commonName: '1 Pedro' }],
    ['2PE', { commonName: '2 Pedro' }],
    ['1JN', { commonName: '1 Juan' }],
    ['2JN', { commonName: '2 Juan' }],
    ['3JN', { commonName: '3 Juan' }],
    ['JUD', { commonName: 'Judas' }],
    ['REV', { commonName: 'Apocalipsis' }],
]);

/**
 * French book names
 */
export const frenchBookMap: BookNameMap = new Map([
    ['GEN', { commonName: 'Genèse' }],
    ['EXO', { commonName: 'Exode' }],
    ['LEV', { commonName: 'Lévitique' }],
    ['NUM', { commonName: 'Nombres' }],
    ['DEU', { commonName: 'Deutéronome' }],
    ['JOS', { commonName: 'Josué' }],
    ['JDG', { commonName: 'Juges' }],
    ['RUT', { commonName: 'Ruth' }],
    ['1SA', { commonName: '1 Samuel' }],
    ['2SA', { commonName: '2 Samuel' }],
    ['1KI', { commonName: '1 Rois' }],
    ['2KI', { commonName: '2 Rois' }],
    ['1CH', { commonName: '1 Chroniques' }],
    ['2CH', { commonName: '2 Chroniques' }],
    ['EZR', { commonName: 'Esdras' }],
    ['NEH', { commonName: 'Néhémie' }],
    ['EST', { commonName: 'Esther' }],
    ['JOB', { commonName: 'Job' }],
    ['PSA', { commonName: 'Psaumes' }],
    ['PRO', { commonName: 'Proverbes' }],
    ['ECC', { commonName: 'Ecclésiaste' }],
    ['SNG', { commonName: 'Cantique des Cantiques' }],
    ['ISA', { commonName: 'Ésaïe' }],
    ['JER', { commonName: 'Jérémie' }],
    ['LAM', { commonName: 'Lamentations' }],
    ['EZK', { commonName: 'Ézéchiel' }],
    ['DAN', { commonName: 'Daniel' }],
    ['HOS', { commonName: 'Osée' }],
    ['JOL', { commonName: 'Joël' }],
    ['AMO', { commonName: 'Amos' }],
    ['OBA', { commonName: 'Abdias' }],
    ['JON', { commonName: 'Jonas' }],
    ['MIC', { commonName: 'Michée' }],
    ['NAM', { commonName: 'Nahum' }],
    ['HAB', { commonName: 'Habacuc' }],
    ['ZEP', { commonName: 'Sophonie' }],
    ['HAG', { commonName: 'Aggée' }],
    ['ZEC', { commonName: 'Zacharie' }],
    ['MAL', { commonName: 'Malachie' }],
    ['MAT', { commonName: 'Matthieu' }],
    ['MRK', { commonName: 'Marc' }],
    ['LUK', { commonName: 'Luc' }],
    ['JHN', { commonName: 'Jean' }],
    ['ACT', { commonName: 'Actes' }],
    ['ROM', { commonName: 'Romains' }],
    ['1CO', { commonName: '1 Corinthiens' }],
    ['2CO', { commonName: '2 Corinthiens' }],
    ['GAL', { commonName: 'Galates' }],
    ['EPH', { commonName: 'Éphésiens' }],
    ['PHP', { commonName: 'Philippiens' }],
    ['COL', { commonName: 'Colossiens' }],
    ['1TH', { commonName: '1 Thessaloniciens' }],
    ['2TH', { commonName: '2 Thessaloniciens' }],
    ['1TI', { commonName: '1 Timothée' }],
    ['2TI', { commonName: '2 Timothée' }],
    ['TIT', { commonName: 'Tite' }],
    ['PHM', { commonName: 'Philémon' }],
    ['HEB', { commonName: 'Hébreux' }],
    ['JAS', { commonName: 'Jacques' }],
    ['1PE', { commonName: '1 Pierre' }],
    ['2PE', { commonName: '2 Pierre' }],
    ['1JN', { commonName: '1 Jean' }],
    ['2JN', { commonName: '2 Jean' }],
    ['3JN', { commonName: '3 Jean' }],
    ['JUD', { commonName: 'Jude' }],
    ['REV', { commonName: 'Apocalypse' }],
]);

/**
 * German book names
 */
export const germanBookMap: BookNameMap = new Map([
    ['GEN', { commonName: '1. Mose' }],
    ['EXO', { commonName: '2. Mose' }],
    ['LEV', { commonName: '3. Mose' }],
    ['NUM', { commonName: '4. Mose' }],
    ['DEU', { commonName: '5. Mose' }],
    ['JOS', { commonName: 'Josua' }],
    ['JDG', { commonName: 'Richter' }],
    ['RUT', { commonName: 'Rut' }],
    ['1SA', { commonName: '1. Samuel' }],
    ['2SA', { commonName: '2. Samuel' }],
    ['1KI', { commonName: '1. Könige' }],
    ['2KI', { commonName: '2. Könige' }],
    ['1CH', { commonName: '1. Chronik' }],
    ['2CH', { commonName: '2. Chronik' }],
    ['EZR', { commonName: 'Esra' }],
    ['NEH', { commonName: 'Nehemia' }],
    ['EST', { commonName: 'Ester' }],
    ['JOB', { commonName: 'Hiob' }],
    ['PSA', { commonName: 'Psalmen' }],
    ['PRO', { commonName: 'Sprüche' }],
    ['ECC', { commonName: 'Prediger' }],
    ['SNG', { commonName: 'Hohelied' }],
    ['ISA', { commonName: 'Jesaja' }],
    ['JER', { commonName: 'Jeremia' }],
    ['LAM', { commonName: 'Klagelieder' }],
    ['EZK', { commonName: 'Hesekiel' }],
    ['DAN', { commonName: 'Daniel' }],
    ['HOS', { commonName: 'Hosea' }],
    ['JOL', { commonName: 'Joel' }],
    ['AMO', { commonName: 'Amos' }],
    ['OBA', { commonName: 'Obadja' }],
    ['JON', { commonName: 'Jona' }],
    ['MIC', { commonName: 'Micha' }],
    ['NAM', { commonName: 'Nahum' }],
    ['HAB', { commonName: 'Habakuk' }],
    ['ZEP', { commonName: 'Zefanja' }],
    ['HAG', { commonName: 'Haggai' }],
    ['ZEC', { commonName: 'Sacharja' }],
    ['MAL', { commonName: 'Maleachi' }],
    ['MAT', { commonName: 'Matthäus' }],
    ['MRK', { commonName: 'Markus' }],
    ['LUK', { commonName: 'Lukas' }],
    ['JHN', { commonName: 'Johannes' }],
    ['ACT', { commonName: 'Apostelgeschichte' }],
    ['ROM', { commonName: 'Römer' }],
    ['1CO', { commonName: '1. Korinther' }],
    ['2CO', { commonName: '2. Korinther' }],
    ['GAL', { commonName: 'Galater' }],
    ['EPH', { commonName: 'Epheser' }],
    ['PHP', { commonName: 'Philipper' }],
    ['COL', { commonName: 'Kolosser' }],
    ['1TH', { commonName: '1. Thessalonicher' }],
    ['2TH', { commonName: '2. Thessalonicher' }],
    ['1TI', { commonName: '1. Timotheus' }],
    ['2TI', { commonName: '2. Timotheus' }],
    ['TIT', { commonName: 'Titus' }],
    ['PHM', { commonName: 'Philemon' }],
    ['HEB', { commonName: 'Hebräer' }],
    ['JAS', { commonName: 'Jakobus' }],
    ['1PE', { commonName: '1. Petrus' }],
    ['2PE', { commonName: '2. Petrus' }],
    ['1JN', { commonName: '1. Johannes' }],
    ['2JN', { commonName: '2. Johannes' }],
    ['3JN', { commonName: '3. Johannes' }],
    ['JUD', { commonName: 'Judas' }],
    ['REV', { commonName: 'Offenbarung' }],
]);

/**
 * Portuguese book names
 */
export const portugueseBookMap: BookNameMap = new Map([
    ['GEN', { commonName: 'Gênesis' }],
    ['EXO', { commonName: 'Êxodo' }],
    ['LEV', { commonName: 'Levítico' }],
    ['NUM', { commonName: 'Números' }],
    ['DEU', { commonName: 'Deuteronômio' }],
    ['JOS', { commonName: 'Josué' }],
    ['JDG', { commonName: 'Juízes' }],
    ['RUT', { commonName: 'Rute' }],
    ['1SA', { commonName: '1 Samuel' }],
    ['2SA', { commonName: '2 Samuel' }],
    ['1KI', { commonName: '1 Reis' }],
    ['2KI', { commonName: '2 Reis' }],
    ['1CH', { commonName: '1 Crônicas' }],
    ['2CH', { commonName: '2 Crônicas' }],
    ['EZR', { commonName: 'Esdras' }],
    ['NEH', { commonName: 'Neemias' }],
    ['EST', { commonName: 'Ester' }],
    ['JOB', { commonName: 'Jó' }],
    ['PSA', { commonName: 'Salmos' }],
    ['PRO', { commonName: 'Provérbios' }],
    ['ECC', { commonName: 'Eclesiastes' }],
    ['SNG', { commonName: 'Cânticos' }],
    ['ISA', { commonName: 'Isaías' }],
    ['JER', { commonName: 'Jeremias' }],
    ['LAM', { commonName: 'Lamentações' }],
    ['EZK', { commonName: 'Ezequiel' }],
    ['DAN', { commonName: 'Daniel' }],
    ['HOS', { commonName: 'Oséias' }],
    ['JOL', { commonName: 'Joel' }],
    ['AMO', { commonName: 'Amós' }],
    ['OBA', { commonName: 'Obadias' }],
    ['JON', { commonName: 'Jonas' }],
    ['MIC', { commonName: 'Miquéias' }],
    ['NAM', { commonName: 'Naum' }],
    ['HAB', { commonName: 'Habacuque' }],
    ['ZEP', { commonName: 'Sofonias' }],
    ['HAG', { commonName: 'Ageu' }],
    ['ZEC', { commonName: 'Zacarias' }],
    ['MAL', { commonName: 'Malaquias' }],
    ['MAT', { commonName: 'Mateus' }],
    ['MRK', { commonName: 'Marcos' }],
    ['LUK', { commonName: 'Lucas' }],
    ['JHN', { commonName: 'João' }],
    ['ACT', { commonName: 'Atos' }],
    ['ROM', { commonName: 'Romanos' }],
    ['1CO', { commonName: '1 Coríntios' }],
    ['2CO', { commonName: '2 Coríntios' }],
    ['GAL', { commonName: 'Gálatas' }],
    ['EPH', { commonName: 'Efésios' }],
    ['PHP', { commonName: 'Filipenses' }],
    ['COL', { commonName: 'Colossenses' }],
    ['1TH', { commonName: '1 Tessalonicenses' }],
    ['2TH', { commonName: '2 Tessalonicenses' }],
    ['1TI', { commonName: '1 Timóteo' }],
    ['2TI', { commonName: '2 Timóteo' }],
    ['TIT', { commonName: 'Tito' }],
    ['PHM', { commonName: 'Filemom' }],
    ['HEB', { commonName: 'Hebreus' }],
    ['JAS', { commonName: 'Tiago' }],
    ['1PE', { commonName: '1 Pedro' }],
    ['2PE', { commonName: '2 Pedro' }],
    ['1JN', { commonName: '1 João' }],
    ['2JN', { commonName: '2 João' }],
    ['3JN', { commonName: '3 João' }],
    ['JUD', { commonName: 'Judas' }],
    ['REV', { commonName: 'Apocalipse' }],
]);

/**
 * Russian book names
 */
export const russianBookMap: BookNameMap = new Map([
    ['GEN', { commonName: 'Бытие' }],
    ['EXO', { commonName: 'Исход' }],
    ['LEV', { commonName: 'Левит' }],
    ['NUM', { commonName: 'Числа' }],
    ['DEU', { commonName: 'Второзаконие' }],
    ['JOS', { commonName: 'Иисус Навин' }],
    ['JDG', { commonName: 'Судьи' }],
    ['RUT', { commonName: 'Руфь' }],
    ['1SA', { commonName: '1 Царств' }],
    ['2SA', { commonName: '2 Царств' }],
    ['1KI', { commonName: '3 Царств' }],
    ['2KI', { commonName: '4 Царств' }],
    ['1CH', { commonName: '1 Паралипоменон' }],
    ['2CH', { commonName: '2 Паралипоменон' }],
    ['EZR', { commonName: 'Ездра' }],
    ['NEH', { commonName: 'Неемия' }],
    ['EST', { commonName: 'Есфирь' }],
    ['JOB', { commonName: 'Иов' }],
    ['PSA', { commonName: 'Псалтирь' }],
    ['PRO', { commonName: 'Притчи' }],
    ['ECC', { commonName: 'Екклесиаст' }],
    ['SNG', { commonName: 'Песнь Песней' }],
    ['ISA', { commonName: 'Исаия' }],
    ['JER', { commonName: 'Иеремия' }],
    ['LAM', { commonName: 'Плач Иеремии' }],
    ['EZK', { commonName: 'Иезекииль' }],
    ['DAN', { commonName: 'Даниил' }],
    ['HOS', { commonName: 'Осия' }],
    ['JOL', { commonName: 'Иоиль' }],
    ['AMO', { commonName: 'Амос' }],
    ['OBA', { commonName: 'Авдий' }],
    ['JON', { commonName: 'Иона' }],
    ['MIC', { commonName: 'Михей' }],
    ['NAM', { commonName: 'Наум' }],
    ['HAB', { commonName: 'Аввакум' }],
    ['ZEP', { commonName: 'Софония' }],
    ['HAG', { commonName: 'Аггей' }],
    ['ZEC', { commonName: 'Захария' }],
    ['MAL', { commonName: 'Малахия' }],
    ['MAT', { commonName: 'Матфея' }],
    ['MRK', { commonName: 'Марка' }],
    ['LUK', { commonName: 'Луки' }],
    ['JHN', { commonName: 'Иоанна' }],
    ['ACT', { commonName: 'Деяния' }],
    ['ROM', { commonName: 'Римлянам' }],
    ['1CO', { commonName: '1 Коринфянам' }],
    ['2CO', { commonName: '2 Коринфянам' }],
    ['GAL', { commonName: 'Галатам' }],
    ['EPH', { commonName: 'Ефесянам' }],
    ['PHP', { commonName: 'Филиппийцам' }],
    ['COL', { commonName: 'Колоссянам' }],
    ['1TH', { commonName: '1 Фессалоникийцам' }],
    ['2TH', { commonName: '2 Фессалоникийцам' }],
    ['1TI', { commonName: '1 Тимофею' }],
    ['2TI', { commonName: '2 Тимофею' }],
    ['TIT', { commonName: 'Титу' }],
    ['PHM', { commonName: 'Филимону' }],
    ['HEB', { commonName: 'Евреям' }],
    ['JAS', { commonName: 'Иакова' }],
    ['1PE', { commonName: '1 Петра' }],
    ['2PE', { commonName: '2 Петра' }],
    ['1JN', { commonName: '1 Иоанна' }],
    ['2JN', { commonName: '2 Иоанна' }],
    ['3JN', { commonName: '3 Иоанна' }],
    ['JUD', { commonName: 'Иуды' }],
    ['REV', { commonName: 'Откровение' }],
]);

/**
 * Chinese Simplified book names
 */
export const chineseSimplifiedBookMap: BookNameMap = new Map([
    ['GEN', { commonName: '创世记' }],
    ['EXO', { commonName: '出埃及记' }],
    ['LEV', { commonName: '利未记' }],
    ['NUM', { commonName: '民数记' }],
    ['DEU', { commonName: '申命记' }],
    ['JOS', { commonName: '约书亚记' }],
    ['JDG', { commonName: '士师记' }],
    ['RUT', { commonName: '路得记' }],
    ['1SA', { commonName: '撒母耳记上' }],
    ['2SA', { commonName: '撒母耳记下' }],
    ['1KI', { commonName: '列王纪上' }],
    ['2KI', { commonName: '列王纪下' }],
    ['1CH', { commonName: '历代志上' }],
    ['2CH', { commonName: '历代志下' }],
    ['EZR', { commonName: '以斯拉记' }],
    ['NEH', { commonName: '尼希米记' }],
    ['EST', { commonName: '以斯帖记' }],
    ['JOB', { commonName: '约伯记' }],
    ['PSA', { commonName: '诗篇' }],
    ['PRO', { commonName: '箴言' }],
    ['ECC', { commonName: '传道书' }],
    ['SNG', { commonName: '雅歌' }],
    ['ISA', { commonName: '以赛亚书' }],
    ['JER', { commonName: '耶利米书' }],
    ['LAM', { commonName: '耶利米哀歌' }],
    ['EZK', { commonName: '以西结书' }],
    ['DAN', { commonName: '但以理书' }],
    ['HOS', { commonName: '何西阿书' }],
    ['JOL', { commonName: '约珥书' }],
    ['AMO', { commonName: '阿摩司书' }],
    ['OBA', { commonName: '俄巴底亚书' }],
    ['JON', { commonName: '约拿书' }],
    ['MIC', { commonName: '弥迦书' }],
    ['NAM', { commonName: '那鸿书' }],
    ['HAB', { commonName: '哈巴谷书' }],
    ['ZEP', { commonName: '西番雅书' }],
    ['HAG', { commonName: '哈该书' }],
    ['ZEC', { commonName: '撒迦利亚书' }],
    ['MAL', { commonName: '玛拉基书' }],
    ['MAT', { commonName: '马太福音' }],
    ['MRK', { commonName: '马可福音' }],
    ['LUK', { commonName: '路加福音' }],
    ['JHN', { commonName: '约翰福音' }],
    ['ACT', { commonName: '使徒行传' }],
    ['ROM', { commonName: '罗马书' }],
    ['1CO', { commonName: '哥林多前书' }],
    ['2CO', { commonName: '哥林多后书' }],
    ['GAL', { commonName: '加拉太书' }],
    ['EPH', { commonName: '以弗所书' }],
    ['PHP', { commonName: '腓立比书' }],
    ['COL', { commonName: '歌罗西书' }],
    ['1TH', { commonName: '帖撒罗尼迦前书' }],
    ['2TH', { commonName: '帖撒罗尼迦后书' }],
    ['1TI', { commonName: '提摩太前书' }],
    ['2TI', { commonName: '提摩太后书' }],
    ['TIT', { commonName: '提多书' }],
    ['PHM', { commonName: '腓利门书' }],
    ['HEB', { commonName: '希伯来书' }],
    ['JAS', { commonName: '雅各书' }],
    ['1PE', { commonName: '彼得前书' }],
    ['2PE', { commonName: '彼得后书' }],
    ['1JN', { commonName: '约翰一书' }],
    ['2JN', { commonName: '约翰二书' }],
    ['3JN', { commonName: '约翰三书' }],
    ['JUD', { commonName: '犹大书' }],
    ['REV', { commonName: '启示录' }],
]);

/**
 * Italian book names
 */
export const italianBookMap: BookNameMap = new Map([
    ['GEN', { commonName: 'Genesi' }],
    ['EXO', { commonName: 'Esodo' }],
    ['LEV', { commonName: 'Levitico' }],
    ['NUM', { commonName: 'Numeri' }],
    ['DEU', { commonName: 'Deuteronomio' }],
    ['JOS', { commonName: 'Giosuè' }],
    ['JDG', { commonName: 'Giudici' }],
    ['RUT', { commonName: 'Rut' }],
    ['1SA', { commonName: '1 Samuele' }],
    ['2SA', { commonName: '2 Samuele' }],
    ['1KI', { commonName: '1 Re' }],
    ['2KI', { commonName: '2 Re' }],
    ['1CH', { commonName: '1 Cronache' }],
    ['2CH', { commonName: '2 Cronache' }],
    ['EZR', { commonName: 'Esdra' }],
    ['NEH', { commonName: 'Neemia' }],
    ['EST', { commonName: 'Ester' }],
    ['JOB', { commonName: 'Giobbe' }],
    ['PSA', { commonName: 'Salmi' }],
    ['PRO', { commonName: 'Proverbi' }],
    ['ECC', { commonName: 'Ecclesiaste' }],
    ['SNG', { commonName: 'Cantico dei Cantici' }],
    ['ISA', { commonName: 'Isaia' }],
    ['JER', { commonName: 'Geremia' }],
    ['LAM', { commonName: 'Lamentazioni' }],
    ['EZK', { commonName: 'Ezechiele' }],
    ['DAN', { commonName: 'Daniele' }],
    ['HOS', { commonName: 'Osea' }],
    ['JOL', { commonName: 'Gioele' }],
    ['AMO', { commonName: 'Amos' }],
    ['OBA', { commonName: 'Abdia' }],
    ['JON', { commonName: 'Giona' }],
    ['MIC', { commonName: 'Michea' }],
    ['NAM', { commonName: 'Naum' }],
    ['HAB', { commonName: 'Abacuc' }],
    ['ZEP', { commonName: 'Sofonia' }],
    ['HAG', { commonName: 'Aggeo' }],
    ['ZEC', { commonName: 'Zaccaria' }],
    ['MAL', { commonName: 'Malachia' }],
    ['MAT', { commonName: 'Matteo' }],
    ['MRK', { commonName: 'Marco' }],
    ['LUK', { commonName: 'Luca' }],
    ['JHN', { commonName: 'Giovanni' }],
    ['ACT', { commonName: 'Atti' }],
    ['ROM', { commonName: 'Romani' }],
    ['1CO', { commonName: '1 Corinzi' }],
    ['2CO', { commonName: '2 Corinzi' }],
    ['GAL', { commonName: 'Galati' }],
    ['EPH', { commonName: 'Efesini' }],
    ['PHP', { commonName: 'Filippesi' }],
    ['COL', { commonName: 'Colossesi' }],
    ['1TH', { commonName: '1 Tessalonicesi' }],
    ['2TH', { commonName: '2 Tessalonicesi' }],
    ['1TI', { commonName: '1 Timoteo' }],
    ['2TI', { commonName: '2 Timoteo' }],
    ['TIT', { commonName: 'Tito' }],
    ['PHM', { commonName: 'Filemone' }],
    ['HEB', { commonName: 'Ebrei' }],
    ['JAS', { commonName: 'Giacomo' }],
    ['1PE', { commonName: '1 Pietro' }],
    ['2PE', { commonName: '2 Pietro' }],
    ['1JN', { commonName: '1 Giovanni' }],
    ['2JN', { commonName: '2 Giovanni' }],
    ['3JN', { commonName: '3 Giovanni' }],
    ['JUD', { commonName: 'Giuda' }],
    ['REV', { commonName: 'Apocalisse' }],
]);

/**
 * Polish book names
 */
export const polishBookMap: BookNameMap = new Map([
    ['GEN', { commonName: 'Rodzaju' }],
    ['EXO', { commonName: 'Wyjścia' }],
    ['LEV', { commonName: 'Kapłańska' }],
    ['NUM', { commonName: 'Liczb' }],
    ['DEU', { commonName: 'Powtórzonego Prawa' }],
    ['JOS', { commonName: 'Jozuego' }],
    ['JDG', { commonName: 'Sędziów' }],
    ['RUT', { commonName: 'Rut' }],
    ['1SA', { commonName: '1 Samuela' }],
    ['2SA', { commonName: '2 Samuela' }],
    ['1KI', { commonName: '1 Królewska' }],
    ['2KI', { commonName: '2 Królewska' }],
    ['1CH', { commonName: '1 Kronik' }],
    ['2CH', { commonName: '2 Kronik' }],
    ['EZR', { commonName: 'Ezdrasza' }],
    ['NEH', { commonName: 'Nehemiasza' }],
    ['EST', { commonName: 'Estery' }],
    ['JOB', { commonName: 'Hioba' }],
    ['PSA', { commonName: 'Psalmów' }],
    ['PRO', { commonName: 'Przysłów' }],
    ['ECC', { commonName: 'Kaznodziei' }],
    ['SNG', { commonName: 'Pieśń nad Pieśniami' }],
    ['ISA', { commonName: 'Izajasza' }],
    ['JER', { commonName: 'Jeremiasza' }],
    ['LAM', { commonName: 'Lamentacje' }],
    ['EZK', { commonName: 'Ezechiela' }],
    ['DAN', { commonName: 'Daniela' }],
    ['HOS', { commonName: 'Ozeasza' }],
    ['JOL', { commonName: 'Joela' }],
    ['AMO', { commonName: 'Amosa' }],
    ['OBA', { commonName: 'Abdiasza' }],
    ['JON', { commonName: 'Jonasza' }],
    ['MIC', { commonName: 'Micheasza' }],
    ['NAM', { commonName: 'Nahuma' }],
    ['HAB', { commonName: 'Habakuka' }],
    ['ZEP', { commonName: 'Sofoniasza' }],
    ['HAG', { commonName: 'Aggeusza' }],
    ['ZEC', { commonName: 'Zachariasza' }],
    ['MAL', { commonName: 'Malachiasza' }],
    ['MAT', { commonName: 'Mateusza' }],
    ['MRK', { commonName: 'Marka' }],
    ['LUK', { commonName: 'Łukasza' }],
    ['JHN', { commonName: 'Jana' }],
    ['ACT', { commonName: 'Dzieje Apostolskie' }],
    ['ROM', { commonName: 'Rzymian' }],
    ['1CO', { commonName: '1 Koryntian' }],
    ['2CO', { commonName: '2 Koryntian' }],
    ['GAL', { commonName: 'Galatów' }],
    ['EPH', { commonName: 'Efezjan' }],
    ['PHP', { commonName: 'Filipian' }],
    ['COL', { commonName: 'Kolosan' }],
    ['1TH', { commonName: '1 Tesaloniczan' }],
    ['2TH', { commonName: '2 Tesaloniczan' }],
    ['1TI', { commonName: '1 Tymoteusza' }],
    ['2TI', { commonName: '2 Tymoteusza' }],
    ['TIT', { commonName: 'Tytusa' }],
    ['PHM', { commonName: 'Filemona' }],
    ['HEB', { commonName: 'Hebrajczyków' }],
    ['JAS', { commonName: 'Jakuba' }],
    ['1PE', { commonName: '1 Piotra' }],
    ['2PE', { commonName: '2 Piotra' }],
    ['1JN', { commonName: '1 Jana' }],
    ['2JN', { commonName: '2 Jana' }],
    ['3JN', { commonName: '3 Jana' }],
    ['JUD', { commonName: 'Judy' }],
    ['REV', { commonName: 'Objawienie' }],
]);

/**
 * Dutch book names
 */
export const dutchBookMap: BookNameMap = new Map([
    ['GEN', { commonName: 'Genesis' }],
    ['EXO', { commonName: 'Exodus' }],
    ['LEV', { commonName: 'Leviticus' }],
    ['NUM', { commonName: 'Numeri' }],
    ['DEU', { commonName: 'Deuteronomium' }],
    ['JOS', { commonName: 'Jozua' }],
    ['JDG', { commonName: 'Richteren' }],
    ['RUT', { commonName: 'Ruth' }],
    ['1SA', { commonName: '1 Samuël' }],
    ['2SA', { commonName: '2 Samuël' }],
    ['1KI', { commonName: '1 Koningen' }],
    ['2KI', { commonName: '2 Koningen' }],
    ['1CH', { commonName: '1 Kronieken' }],
    ['2CH', { commonName: '2 Kronieken' }],
    ['EZR', { commonName: 'Ezra' }],
    ['NEH', { commonName: 'Nehemia' }],
    ['EST', { commonName: 'Esther' }],
    ['JOB', { commonName: 'Job' }],
    ['PSA', { commonName: 'Psalmen' }],
    ['PRO', { commonName: 'Spreuken' }],
    ['ECC', { commonName: 'Prediker' }],
    ['SNG', { commonName: 'Hooglied' }],
    ['ISA', { commonName: 'Jesaja' }],
    ['JER', { commonName: 'Jeremia' }],
    ['LAM', { commonName: 'Klaagliederen' }],
    ['EZK', { commonName: 'Ezechiël' }],
    ['DAN', { commonName: 'Daniël' }],
    ['HOS', { commonName: 'Hosea' }],
    ['JOL', { commonName: 'Joël' }],
    ['AMO', { commonName: 'Amos' }],
    ['OBA', { commonName: 'Obadja' }],
    ['JON', { commonName: 'Jona' }],
    ['MIC', { commonName: 'Micha' }],
    ['NAM', { commonName: 'Nahum' }],
    ['HAB', { commonName: 'Habakuk' }],
    ['ZEP', { commonName: 'Sefanja' }],
    ['HAG', { commonName: 'Haggaï' }],
    ['ZEC', { commonName: 'Zacharia' }],
    ['MAL', { commonName: 'Maleachi' }],
    ['MAT', { commonName: 'Mattheüs' }],
    ['MRK', { commonName: 'Marcus' }],
    ['LUK', { commonName: 'Lucas' }],
    ['JHN', { commonName: 'Johannes' }],
    ['ACT', { commonName: 'Handelingen' }],
    ['ROM', { commonName: 'Romeinen' }],
    ['1CO', { commonName: '1 Korintiërs' }],
    ['2CO', { commonName: '2 Korintiërs' }],
    ['GAL', { commonName: 'Galaten' }],
    ['EPH', { commonName: 'Efeziërs' }],
    ['PHP', { commonName: 'Filippenzen' }],
    ['COL', { commonName: 'Kolossenzen' }],
    ['1TH', { commonName: '1 Tessalonicenzen' }],
    ['2TH', { commonName: '2 Tessalonicenzen' }],
    ['1TI', { commonName: '1 Timoteüs' }],
    ['2TI', { commonName: '2 Timoteüs' }],
    ['TIT', { commonName: 'Titus' }],
    ['PHM', { commonName: 'Filemon' }],
    ['HEB', { commonName: 'Hebreeën' }],
    ['JAS', { commonName: 'Jakobus' }],
    ['1PE', { commonName: '1 Petrus' }],
    ['2PE', { commonName: '2 Petrus' }],
    ['1JN', { commonName: '1 Johannes' }],
    ['2JN', { commonName: '2 Johannes' }],
    ['3JN', { commonName: '3 Johannes' }],
    ['JUD', { commonName: 'Judas' }],
    ['REV', { commonName: 'Openbaring' }],
]);

/**
 * Map of language codes to book name maps.
 * This extends the existing bookIdMap in book-order.ts
 */
export const additionalBookIdMap = new Map<string, BookNameMap>([
    // Romanian
    ['ro', romanianBookMap],
    ['ron', romanianBookMap],
    ['rum', romanianBookMap],

    // Spanish
    ['es', spanishBookMap],
    ['spa', spanishBookMap],

    // French
    ['fr', frenchBookMap],
    ['fra', frenchBookMap],
    ['fre', frenchBookMap],

    // German
    ['de', germanBookMap],
    ['deu', germanBookMap],
    ['ger', germanBookMap],

    // Portuguese
    ['pt', portugueseBookMap],
    ['por', portugueseBookMap],

    // Russian
    ['ru', russianBookMap],
    ['rus', russianBookMap],

    // Chinese Simplified
    ['zh', chineseSimplifiedBookMap],
    ['zho', chineseSimplifiedBookMap],
    ['chi', chineseSimplifiedBookMap],
    ['cmn', chineseSimplifiedBookMap],

    // Italian
    ['it', italianBookMap],
    ['ita', italianBookMap],

    // Polish
    ['pl', polishBookMap],
    ['pol', polishBookMap],

    // Dutch
    ['nl', dutchBookMap],
    ['nld', dutchBookMap],
    ['dut', dutchBookMap],
]);

/**
 * Gets a book name map for the specified language code.
 * Falls back to null if the language is not found.
 */
export function getBookNameMap(languageCode: string): BookNameMap | null {
    return additionalBookIdMap.get(languageCode.toLowerCase()) ?? null;
}

/**
 * Gets a book name for the specified language and book ID.
 * Falls back to null if not found.
 */
export function getBookName(
    languageCode: string,
    bookId: string
): string | null {
    const map = getBookNameMap(languageCode);
    if (!map) return null;
    return map.get(bookId)?.commonName ?? null;
}
